/**
 * This code was generated by Builder.io.
 */
import React from "react";

function ChartActivity() {
  const weeks = Array.from(
    { length: 10 },
    (_, i) => `Week ${String(i + 1).padStart(2, "0")}`
  );

  return (
    <section className="flex flex-col items-start px-7 pt-3.5 pb-9 mt-3.5 w-full text-sm bg-white rounded-3xl shadow-[0px_4px_6px_rgba(62,73,84,0.04)] max-md:px-5 max-md:max-w-full">
      <div className="flex flex-wrap gap-5 justify-between w-full text-lg font-bold max-w-[1187px] max-md:max-w-full">
        <h2 className="my-auto text-black">Chart Activity</h2>
        <div className="flex gap-10 px-5 py-5 text-blue-600 bg-sky-200 rounded-xl border border-blue-600 border-solid">
          <span>This Month</span>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/a9cdd601eda734fa124518d9298722eeac5226925819dd5b64ecd93fa3f75194?placeholderIfAbsent=true&apiKey=b9ca3c09dab7473dba421305306c78ba"
            alt=""
            className="object-contain shrink-0 self-start mt-3 aspect-[2.43] w-[17px]"
          />
        </div>
      </div>
      <div className="flex shrink-0 self-stretch mt-11 h-px bg-violet-100 rounded-3xl max-md:mt-10 max-md:max-w-full" />
      {[80, 60, 40, 20, 0].map((value, index) => (
        <div
          key={index}
          className={`mt-${index === 0 ? "8" : index === 4 ? "12" : "11"} ml-${
            index === 4 ? "6" : "3.5"
          } text-neutral-500 max-md:mt-10 max-md:ml-2.5`}
        >
          {value}
        </div>
      ))}
      <div className="flex shrink-0 self-stretch mt-3.5 h-px bg-violet-100 rounded-3xl max-md:max-w-full" />
      <div className="flex flex-wrap gap-10 self-center mt-3.5 w-full max-w-[1104px] text-slate-500 max-md:max-w-full">
        {weeks.map((week, index) => (
          <div key={index} className={index === 0 ? "grow" : ""}>
            {week}
          </div>
        ))}
      </div>
      <div className="flex gap-5 justify-between self-center mt-16 ml-14 max-w-full whitespace-nowrap text-neutral-900 w-[438px] max-md:mt-10">
        <div className="flex gap-3.5">
          <div className="flex shrink-0 bg-blue-600 rounded-xl h-[22px] w-[22px]" />
          <div>Spendings</div>
        </div>
        <div className="flex gap-3.5">
          <div className="flex shrink-0 bg-green-500 rounded-xl h-[21px] w-[23px]" />
          <div className="self-start">Income</div>
        </div>
        <div className="flex gap-4">
          <div className="flex shrink-0 rounded-xl bg-zinc-300 h-[22px] w-[22px]" />
          <div className="self-start">Others</div>
        </div>
      </div>
    </section>
  );
}

export default ChartActivity;
