/**
 * This code was generated by Builder.io.
 */
import React from 'react';

function FlightsShare() {
  return (
    <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
    <div className="flex flex-col grow pt-8 pr-20 pb-24 pl-5 w-full text-lg font-bold text-black bg-white rounded-xl shadow-[0px_4px_6px_rgba(62,73,84,0.04)] max-md:pr-5 max-md:mt-10 max-md:max-w-full">
    <h3 className="self-start">Flights Share</h3>
    <img 
      loading="lazy" 
      src="https://cdn.builder.io/api/v1/image/assets/TEMP/586f67119379116ddb817569bc923a688ee35c9868bcaeb243f7024da1d3c68d?placeholderIfAbsent=true&apiKey=b9ca3c09dab7473dba421305306c78ba" 
      alt="Flights share pie chart" 
      className="object-contain self-end mt-16 max-w-full aspect-[1.01] w-[313px] max-md:mt-10" 
    />
  </div>
  </div>
  );
}

export default FlightsShare;