/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Header() {
  return (
    <header className="flex flex-wrap gap-5 justify-between w-full max-md:max-w-full">
      <h1 className="my-auto text-2xl font-bold text-black">Dashboard</h1>
      <div className="flex flex-wrap gap-10 max-md:max-w-full">
        <div className="flex flex-auto gap-6 text-xs text-stone-300">
          <form className="flex gap-3 p-2.5 bg-white rounded-xl border border-solid border-zinc-300">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/d8156d08b142747ed020e2c1c5d0f515a002b31f18100d81624e26bf346e4b9a?placeholderIfAbsent=true&apiKey=b9ca3c09dab7473dba421305306c78ba"
              alt=""
              className="object-contain shrink-0 aspect-[0.87] w-[21px]"
            />
            <label htmlFor="search" className="sr-only">
              Search suppliers
            </label>
            <input
              type="text"
              id="search"
              placeholder="Search suppliers..."
              className="my-auto basis-auto"
            />
          </form>
          <button aria-label="Notifications">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/a5519cd2fce528c80c4fda0c8d196d57ef8764bc8574115a0b3d02203dd32faf?placeholderIfAbsent=true&apiKey=b9ca3c09dab7473dba421305306c78ba"
              alt=""
              className="object-contain shrink-0 w-10 aspect-[0.93]"
            />
          </button>
          <button aria-label="Messages">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/f40684d2cbecc1044e49ec6c158e745e4ccd6e8fb8277fc68a0ca2378e2529ba?placeholderIfAbsent=true&apiKey=b9ca3c09dab7473dba421305306c78ba"
              alt=""
              className="object-contain shrink-0 w-10 aspect-[0.93]"
            />
          </button>
          <button aria-label="Settings">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/66b769dbf2e19bb273f40ff734e569a474ee1d324b4df033f2fe2e142daa913f?placeholderIfAbsent=true&apiKey=b9ca3c09dab7473dba421305306c78ba"
              alt=""
              className="object-contain shrink-0 w-10 aspect-[0.93]"
            />
          </button>
        </div>
        <div className="flex gap-1.5 text-right">
          <div className="flex flex-col self-start">
            <div className="text-lg font-bold text-black">Designluch</div>
            <div className="self-start mt-3 ml-4 text-sm text-slate-500 max-md:ml-2.5">
              Super Admin
            </div>
          </div>
          <div
            className="flex shrink-0 border border-solid bg-zinc-300 border-neutral-400 h-[43px] w-[43px]"
            aria-label="User avatar"
          />
          <button aria-label="User menu">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/7626da9aeaa2683e96d702faaf1369e5ba29f7a7703077ef638fc8235f29a0c9?placeholderIfAbsent=true&apiKey=b9ca3c09dab7473dba421305306c78ba"
              alt=""
              className="object-contain shrink-0 my-auto w-6 aspect-square"
            />
          </button>
        </div>
      </div>
    </header>
  );
}

export default Header;
