/**
 * This code was generated by Builder.io.
 */
import React from "react";

function SpendCard({ title, amount, bgColor }) {
  return (
    <div className={`flex flex-col w-6/12 max-md:ml-0 max-md:w-full`}>
      <div
        className={`flex overflow-hidden flex-col grow justify-center items-center px-28 py-11 w-full text-white ${bgColor} rounded-2xl max-md:px-5 max-md:mt-10 max-md:max-w-full`}
      >
        <div className="flex flex-col max-w-full rounded-none w-[156px]">
          <div className="text-lg font-medium">{title}</div>
          <div className="mt-4 text-3xl font-bold max-md:mr-1.5">{amount}</div>
        </div>
      </div>
    </div>
  );
}

export default SpendCard;
