/**
 * This code was generated by Builder.io.
 */
import React from "react";

function TransactionOverview() {
  const yAxisLabels = [100, 80, 60, 40, 20, 0];
  const barData = [
    { green: 161, rose: 207 },
    { green: 268, rose: 137 },
    { green: 80, rose: 52 },
    { green: 215, rose: 132 },
  ];

  return (
    <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
      <div className="flex flex-col items-start px-5 pt-8 pb-14 mx-auto w-full bg-white rounded-xl shadow-[0px_4px_6px_rgba(62,73,84,0.04)] max-md:mt-10 max-md:max-w-full">
        <h3 className="text-lg font-bold text-black">Transaction Overview</h3>
        <div className="flex gap-10 mt-4 max-w-full text-base font-semibold text-black whitespace-nowrap w-[286px]">
          <div className="flex flex-1 gap-3">
            <div className="flex shrink-0 bg-green-500 rounded-full h-[21px] w-[21px]" />
            <div>Income</div>
          </div>
          <div className="flex flex-1 gap-2.5">
            <div className="flex shrink-0 bg-rose-500 rounded-full h-[21px] w-[21px]" />
            <div>Expense</div>
          </div>
        </div>
        <div className="flex gap-10 self-stretch mt-20 max-md:mt-10 max-md:max-w-full">
          <div className="flex flex-col text-sm whitespace-nowrap text-neutral-500 max-md:hidden">
            {yAxisLabels.map((label, index) => (
              <div
                key={index}
                className={`${
                  index === 0
                    ? "self-start"
                    : index === 5
                    ? "mt-12 ml-3"
                    : "mt-11"
                } ${index === 5 ? "max-md:mt-10 max-md:ml-2.5" : ""}`}
              >
                {label}
              </div>
            ))}
          </div>
          <div className="flex flex-col grow shrink-0 self-start py-px mt-2.5 basis-0 w-fit">
            <div className="flex shrink-0 h-0.5 bg-violet-100 rounded-3xl" />
            <div className="flex z-10 gap-10 items-end max-w-full w-[300px]">
              {barData.map((data, index) => (
                <div
                  key={index}
                  className={`flex flex-1 gap-1 ${
                    index === 0
                      ? "mt-16"
                      : index === 1
                      ? "self-stretch"
                      : index === 2
                      ? "mt-48"
                      : "mt-14"
                  } max-md:mt-10`}
                >
                  <div
                    className={`flex shrink-0 ${
                      index !== 2 ? "max-md:hidden" : ""
                    } bg-green-500 rounded-xl h-[${data.green}px] w-[15px]`}
                  />
                  <div
                    className={`flex shrink-0 ${
                      index === 1 || index === 2 ? "self-end" : ""
                    } ${
                      index === 1
                        ? "mt-32"
                        : index === 2
                        ? "mt-7"
                        : index === 3
                        ? "mt-20"
                        : ""
                    } bg-rose-500 rounded-xl h-[${data.rose}px] w-[15px] ${
                      index === 0 ? "max-md:hidden" : ""
                    }`}
                  />
                </div>
              ))}
            </div>
            <div className="flex shrink-0 h-px bg-violet-100 rounded-3xl" />
          </div>
        </div>
      </div>
    </div>
  );
}

export default TransactionOverview;
