/**
 * This code was generated by Builder.io.
 */
import React from "react";

function ContactForm() {
  return (
    <div className="flex flex-col ml-5 w-[70%] max-md:ml-0 max-md:w-full">
      <div className="flex overflow-hidden flex-col grow justify-center px-8 py-10 w-full text-base bg-white rounded shadow-sm max-md:px-5 max-md:mt-8 max-md:max-w-full">
        <form className="flex flex-col items-end w-full max-md:max-w-full">
          <div className="flex flex-wrap gap-4 items-start leading-6 text-red-500 max-md:max-w-full">
            {["Name", "Email", "Phone"].map((field, index) => (
              <div key={index} className="flex flex-col w-[235px]">
                <div className="flex overflow-hidden flex-col justify-center items-start px-4 py-3.5 rounded bg-neutral-100 max-md:pr-5">
                  <label
                    htmlFor={field.toLowerCase()}
                    className="sr-only"
                  >{`Your ${field}`}</label>
                  <input
                    type={field === "Email" ? "email" : "text"}
                    id={field.toLowerCase()}
                    placeholder={`Your ${field}*`}
                    required
                    className="opacity-50 bg-transparent border-none outline-none w-full"
                  />
                </div>
              </div>
            ))}
          </div>
          <div className="flex flex-col mt-8 max-w-full text-black w-[737px]">
            <div className="flex overflow-hidden flex-col items-start px-4 pt-3.5 pb-44 rounded bg-neutral-100 max-md:pr-5 max-md:pb-24 max-md:max-w-full">
              <label htmlFor="message" className="sr-only">
                Your Message
              </label>
              <textarea
                id="message"
                placeholder="Your Message"
                className="opacity-50 bg-transparent border-none outline-none w-full h-full resize-none"
              ></textarea>
            </div>
          </div>
          <button
            type="submit"
            className="gap-2.5 self-end px-12 py-4 mt-8 font-medium bg-red-500 rounded text-neutral-50 max-md:px-5"
          >
            Send Message
          </button>
        </form>
      </div>
    </div>
  );
}

export default ContactForm;
