/**
 * This code was generated by Builder.io.
 */
import React from "react";

function LanguageSelector() {
  return (
    <div className="flex gap-1.5 justify-center items-center my-auto whitespace-nowrap">
      <div className="my-auto">English</div>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/086dd669bbad3e4fcefbf1d6392f774b77d8ae772723fe01a24425e01abcaf04?placeholderIfAbsent=true&apiKey=b9ca3c09dab7473dba421305306c78ba"
        alt=""
        className="object-contain w-6 aspect-square"
      />
    </div>
  );
}

export default LanguageSelector;
