/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "../../components/component/Header";

import ContactSection from "./ContactSection";
import Footer from "./Footer";

function Layout() {
  return (
    <div className="flex overflow-hidden flex-col bg-white">
      <Header />
      <div className="" />
      <main>
        <ContactSection />
      </main>
      <Footer />
    </div>
  );
}

export default Layout;
