/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import ExclusiveHeader from "./ExclusiveHeader";
import ContactSection from "./ContactSection";
import Footer from "./Footer";

function Layout() {
  return (
    <div className="flex overflow-hidden flex-col bg-white">
      <Header />
      <ExclusiveHeader />
      <div className="mt-4 w-full bg-black border border-black border-solid opacity-30 min-h-[1px] max-md:max-w-full" />
      <main>
        <ContactSection />
      </main>
      <Footer />
    </div>
  );
}

export default Layout;
