/**
 * This code was generated by Builder.io.
 */
import React from "react";
import NewsletterSignup from "./NewsletterSignup";
import SocialLinks from "./SocialLinks";

function Footer() {
  return (
    <footer className="flex flex-col justify-end pt-20 pb-6 mt-36 w-full bg-black max-md:mt-10">
      <div className="flex flex-wrap justify-between items-start self-center w-full max-w-screen-xl mx-auto gap-10 px-4 max-md:flex-col max-md:items-center">
        <NewsletterSignup />
        <FooterColumn
          title="Support"
          items={[
            "111 Bijoy sarani, Dhaka, DH 1515, Bangladesh.",
            "exclusive@gmail.com",
            "+88015-88888-9999",
          ]}
        />
        <FooterColumn
          title="Account"
          items={["My Account", "Login / Register", "Cart", "Wishlist", "Shop"]}
        />
        <FooterColumn
          title="Quick Link"
          items={["Privacy Policy", "Terms Of Use", "FAQ", "Contact"]}
        />
        <div className="flex flex-col w-[217px]">
          <h3 className="text-xl font-medium leading-snug text-neutral-50">
            Download App
          </h3>
          <div className="flex flex-col mt-6">
            <p className="text-xs font-medium opacity-70 text-neutral-50">
              Save $3 with App New User Only
            </p>
            <div className="flex gap-2 items-center mt-2">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/6aab00e71b970bdad60cac13646a4eae45c0005ef81fa2d4579b580931834d27?placeholderIfAbsent=true&apiKey=907845159c31450ca87b5b226dbf1f02"
                alt="QR Code"
                className="object-contain w-20 aspect-square"
              />
              <div className="flex flex-col w-[110px]">
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/e4db790075ffc9fa00017c27cace190780dba9226e3a27e04cec8f11ddbfb36b?placeholderIfAbsent=true&apiKey=907845159c31450ca87b5b226dbf1f02"
                  alt="Download on App Store"
                  className="object-contain w-full aspect-[2.75]"
                />
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/89fd8c9820971a1656a784adf3c50ed7d1da9779750c03dfbcff92df5a81bfcd?placeholderIfAbsent=true&apiKey=907845159c31450ca87b5b226dbf1f02"
                  alt="Get it on Google Play"
                  className="object-contain mt-1 w-full aspect-[2.75]"
                />
              </div>
            </div>
          </div>
          <SocialLinks />
        </div>
      </div>
      <div className="flex flex-col items-center mt-16 w-full max-md:mt-10">
        <div className="w-full bg-white border border-white border-solid opacity-40 min-h-[1px]" />
        <div className="flex gap-3 items-center mt-4 text-base text-white">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/d9e77ca5f6362e8c84e9e430400b10a2e9fcc4f4b98d11736abbf6c72292338e?placeholderIfAbsent=true&apiKey=907845159c31450ca87b5b226dbf1f02"
            alt=""
            className="object-contain w-5 aspect-square"
          />
          <p>Copyright Rimel 2022. All rights reserved</p>
        </div>
      </div>
    </footer>
  );
}

function FooterColumn({ title, items }) {
  return (
    <div className="flex flex-col w-[217px] text-neutral-50">
      <h3 className="text-xl font-medium leading-snug">{title}</h3>
      <ul className="flex flex-col mt-6 text-base">
        {items.map((item, index) => (
          <li key={index} className={index > 0 ? "mt-4" : ""}>
            {item}
          </li>
        ))}
      </ul>
    </div>
  );
}

export default Footer;
