/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import WishlistSection from "./WishlistSection";
import JustForYouSection from "./JustForYouSection";
import Footer from "./Footer";

function MainContent() {
  return (
    <div className="flex overflow-hidden flex-col bg-white">
      <Header />
      <main>
        <WishlistSection />
        <JustForYouSection />
      </main>
      <Footer />
    </div>
  );
}

export default MainContent;
