import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react"; // Import SessionProvider
import { StoreProvider } from "../context/StoreContext";
import { UserProvider } from "../context/UserContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
      </head>
      <body className={inter.className}>
        <SessionProvider>
          <UserProvider>
            <StoreProvider>
              {children}
            </StoreProvider>
          </UserProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
