/**
 * This code was generated by Builder.io.
 */
import React from "react";

const AccountNavigation = () => {
  return (
    <nav className="flex flex-col w-full md:w-[20%] p-6 bg-gray-100 rounded-lg shadow-lg">
      <div className="flex flex-col items-start text-base font-medium text-black">
        <h2 className="text-lg font-bold mb-4">Manage My Account</h2>
        <div className="flex flex-col mt-4">
          <a href="/account" className="text-red-500 hover:underline transition duration-200">
            My Profile
          </a>
          <a href="/changes-pass" className="mt-2 text-red-500 hover:underline transition duration-200">
            Changes Password
          </a>
          <a href="#" className="mt-2 opacity-50 hover:opacity-100 transition duration-200">
            My Payment Options
          </a>
        </div>
        <h2 className="mt-6 text-lg font-bold">My Orders</h2>
        <div className="flex flex-col mt-4">
          <a href="/orderstatus" className="opacity-50 hover:opacity-100 transition duration-200">
            My Orders
          </a>
          <a href="#" className="mt-2 opacity-50 hover:opacity-100 transition duration-200">
            My Cancellations
          </a>
        </div>
        <a href="#" className="mt-4 text-red-500 hover:underline transition duration-200">
          My WishList
        </a>
      </div>
    </nav>
  );
};

export default AccountNavigation;
