/**
 * This code was generated by Builder.io.
 */
import React from "react";

const AppDownload = () => {
  return (
    <div className="flex flex-col">
      <h3 className="text-xl font-medium leading-snug text-neutral-50">
        Download App
      </h3>
      <div className="flex flex-col mt-6">
        <p className="text-xs font-medium opacity-70 text-neutral-50">
          Save $3 with App New User Only
        </p>
        <div className="flex gap-2 items-center mt-2">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/6aab00e71b970bdad60cac13646a4eae45c0005ef81fa2d4579b580931834d27?placeholderIfAbsent=true&apiKey=907845159c31450ca87b5b226dbf1f02"
            alt="QR Code"
            className="object-contain shrink-0 self-stretch my-auto w-20 aspect-square"
          />
          <div className="flex flex-col self-stretch my-auto w-[110px]">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/e4db790075ffc9fa00017c27cace190780dba9226e3a27e04cec8f11ddbfb36b?placeholderIfAbsent=true&apiKey=907845159c31450ca87b5b226dbf1f02"
              alt="Download on the App Store"
              className="object-contain max-w-full aspect-[2.75] w-[110px]"
            />
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/89fd8c9820971a1656a784adf3c50ed7d1da9779750c03dfbcff92df5a81bfcd?placeholderIfAbsent=true&apiKey=907845159c31450ca87b5b226dbf1f02"
              alt="Get it on Google Play"
              className="object-contain mt-1 max-w-full aspect-[2.75] w-[110px]"
            />
          </div>
        </div>
      </div>
    </div>
  );
};

export default AppDownload;
