/**
 * This code was generated by Builder.io.
 */
import React from "react";
import NewsletterForm from "./NewsletterForm";
import FooterLinks from "./FooterLinks";
import AppDownload from "./AppDownload";
import SocialLinks from "./SocialLinks";

const Footer = () => {
  return (
    <footer className="flex flex-col justify-between pt-20 pb-6 mt-36 w-full bg-black max-md:mt-10 max-md:max-w-full">
      <div className="flex flex-wrap justify-around items-start gap-10 max-md:max-w-full">
        <NewsletterForm />
        <FooterLinks
          title="Support"
          items={[
            "111 Bijoy sarani, Dhaka, DH 1515, Bangladesh.",
            "exclusive@gmail.com",
            "+88015-88888-9999",
          ]}
        />
        <FooterLinks
          title="Account"
          items={["My Account", "Login / Register", "Cart", "Wishlist", "Shop"]}
        />
        <FooterLinks
          title="Quick Link"
          items={["Privacy Policy", "Terms Of Use", "FAQ", "Contact"]}
        />
        <div className="flex flex-col items-center">
          <AppDownload />
          <SocialLinks />
        </div>
      </div>

      <div className="flex flex-col items-center mt-16 w-full max-md:mt-10">
        <div className="w-full bg-white border border-white border-solid opacity-40 min-h-[1px] max-md:max-w-full" />
        <div className="flex gap-3 items-center mt-4 text-base text-white">
          <div className="flex gap-1.5 items-center self-stretch my-auto min-w-[240px]">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/d9e77ca5f6362e8c84e9e430400b10a2e9fcc4f4b98d11736abbf6c72292338e?placeholderIfAbsent=true&apiKey=907845159c31450ca87b5b226dbf1f02"
              alt=""
              className="object-contain shrink-0 self-stretch my-auto w-5 aspect-square"
            />
            <p className="self-stretch my-auto">
              Copyright Rimel 2022. All rights reserved
            </p>
          </div>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
