/**
 * This code was generated by Builder.io.
 */
import React from "react";

const FooterLinks = ({ title, items }) => {
  return (
    <div className="flex flex-col text-neutral-50 w-[175px]">
      <h3 className="text-xl font-medium leading-snug">{title}</h3>
      <div className="flex flex-col mt-6 max-w-full text-base w-[175px]">
        {items.map((item, index) => (
          <a key={index} href="#" className={index > 0 ? "mt-4" : ""}>
            {item}
          </a>
        ))}
      </div>
    </div>
  );
};

export default FooterLinks;
