/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SearchBar from "./SearchBar";

const Navigation = () => {
  return (
    <nav className="flex flex-wrap gap-10 items-center self-center mt-10 max-md:max-w-full">
      <div className="flex flex-wrap gap-10 items-start self-stretch my-auto text-black min-w-[240px] max-md:max-w-full">
        <h1 className="text-2xl font-bold tracking-wider leading-none whitespace-nowrap w-[118px]">
          Exclusive
        </h1>
        <div className="flex gap-10 items-start text-base text-center min-w-[240px]">
          <a href="#" className="w-12 whitespace-nowrap">
            Home
          </a>
          <a href="#" className="whitespace-nowrap w-[66px]">
            Contact
          </a>
          <a href="#" className="w-12 whitespace-nowrap">
            About
          </a>
          <a href="#" className="w-[61px]">
            Sign Up
          </a>
        </div>
      </div>
      <SearchBar />
      <div className="flex gap-4 justify-center items-center self-stretch my-auto">
        <button aria-label="Wishlist" className="w-8 h-8">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/850597cc14d3bfef027aa097fc5bca3ac1b650d683dc1d3c8c0134d5cd9a061d?placeholderIfAbsent=true&apiKey=907845159c31450ca87b5b226dbf1f02"
            alt=""
            className="object-contain w-full h-full"
          />
        </button>
        <button aria-label="Cart" className="w-8 h-8">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/f1602ef0e88675df931f73ee88ccd85c7a919ff3264f5e5c09b7ad94b1f6df9c?placeholderIfAbsent=true&apiKey=907845159c31450ca87b5b226dbf1f02"
            alt=""
            className="object-contain w-full h-full"
          />
        </button>
        <button aria-label="Profile" className="w-8 h-8">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/5da7135e32227c2b57956f4aeebb39217ace541f01beff22a9a74f318d6ed56d?placeholderIfAbsent=true&apiKey=907845159c31450ca87b5b226dbf1f02"
            alt=""
            className="object-contain w-full h-full fill-red-500"
          />
        </button>
      </div>
    </nav>
  );
};

export default Navigation;
