/**
 * This code was generated by Builder.io.
 */
import React from "react";

const NewsletterForm = () => {
  return (
    <div className="flex flex-col text-neutral-50 w-[217px]">
      <div className="flex flex-col self-start">
        <div className="flex flex-col max-w-full whitespace-nowrap w-[118px]">
          <h2 className="w-full text-2xl font-bold tracking-wider leading-none">
            Exclusive
          </h2>
          <h3 className="mt-6 text-xl font-medium leading-snug">Subscribe</h3>
        </div>
        <p className="mt-6 text-base">Get 10% off your first order</p>
      </div>
      <form className="flex gap-8 items-center py-3 pl-4 mt-4 max-w-full text-base rounded border-solid border-[1.5px] border-neutral-50 w-[217px]">
        <label htmlFor="email" className="sr-only">
          Enter your email
        </label>
        <input
          type="email"
          id="email"
          placeholder="Enter your email"
          className="self-stretch my-auto bg-transparent border-none outline-none text-neutral-50 opacity-40"
        />
        <button type="submit" aria-label="Subscribe">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/12a54082781a806227ade42d81d6722495cd51ed50c28a6b5eebf5a1f9d88295?placeholderIfAbsent=true&apiKey=907845159c31450ca87b5b226dbf1f02"
            alt=""
            className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
          />
        </button>
      </form>
    </div>
  );
};

export default NewsletterForm;
