/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ProfileForm = () => {
  return (
    <form className="flex overflow-hidden flex-col px-20 py-10 mx-auto w-full text-base bg-white rounded shadow-sm max-md:px-5 max-md:mt-10 max-md:max-w-full">
      <h2 className="self-start text-xl font-medium leading-snug text-red-500">
        Edit Your Profile
      </h2>
      <div className="flex flex-wrap gap-10 items-start mt-4 text-black max-md:max-w-full">
        <div className="flex flex-col min-w-[240px] w-[330px]">
          <label htmlFor="firstName">First Name</label>
          <div className="flex flex-col mt-2 max-w-full whitespace-nowrap w-[330px]">
            <input
              type="text"
              id="firstName"
              className="flex overflow-hidden flex-col justify-center items-start px-4 py-3.5 rounded bg-neutral-100 max-md:pr-5"
              placeholder="Md"
            />
          </div>
        </div>
        <div className="flex flex-col min-w-[240px] w-[330px]">
          <label htmlFor="lastName">Last Name</label>
          <div className="flex flex-col mt-2 max-w-full whitespace-nowrap w-[330px]">
            <input
              type="text"
              id="lastName"
              className="flex overflow-hidden flex-col justify-center items-start px-4 py-3.5 rounded bg-neutral-100 max-md:pr-5"
              placeholder="Rimel"
            />
          </div>
        </div>
      </div>
      <div className="flex flex-wrap gap-10 items-start mt-6 text-black max-md:max-w-full">
        <div className="flex flex-col whitespace-nowrap min-w-[240px] w-[330px]">
          <label htmlFor="email">Email</label>
          <div className="flex flex-col mt-2 max-w-full w-[330px]">
            <input
              type="email"
              id="email"
              className="flex overflow-hidden flex-col justify-center items-start px-4 py-3.5 rounded bg-neutral-100 max-md:pr-5"
              placeholder="rimel1111@gmail.com"
            />
          </div>
        </div>
        <div className="flex flex-col min-w-[240px] w-[330px]">
          <label htmlFor="address">Address</label>
          <div className="flex flex-col mt-2 max-w-full w-[330px]">
            <input
              type="text"
              id="address"
              className="flex overflow-hidden flex-col justify-center items-start px-4 py-3.5 rounded bg-neutral-100 max-md:pr-5"
              placeholder="Kingston, 5236, United State"
            />
          </div>
        </div>
      </div>
      <div className="flex flex-col mt-6 text-black max-md:max-w-full">
        <div className="flex flex-col max-w-full w-[710px]">
          <label htmlFor="currentPassword">Password Changes</label>
          <div className="flex flex-col mt-2 w-full">
            <input
              type="password"
              id="currentPassword"
              className="flex overflow-hidden flex-col justify-center items-start px-4 py-3.5 rounded bg-neutral-100 max-md:pr-5 max-md:max-w-full"
              placeholder="Current Password"
            />
          </div>
        </div>
        <div className="flex flex-col mt-4 max-w-full w-[710px]">
          <input
            type="password"
            id="newPassword"
            className="flex overflow-hidden flex-col justify-center items-start px-4 py-3.5 rounded bg-neutral-100 max-md:pr-5 max-md:max-w-full"
            placeholder="New Password"
          />
        </div>
        <div className="flex flex-col mt-4 max-w-full w-[710px]">
          <input
            type="password"
            id="confirmPassword"
            className="flex overflow-hidden flex-col justify-center items-start px-4 py-3.5 rounded bg-neutral-100 max-md:pr-5 max-md:max-w-full"
            placeholder="Confirm New Password"
          />
        </div>
      </div>
      <div className="flex gap-8 items-center self-end mt-6">
        <button type="button" className="self-stretch my-auto text-black">
          Cancel
        </button>
        <button
          type="submit"
          className="gap-2.5 self-stretch px-12 py-4 my-auto font-medium bg-red-500 rounded text-neutral-50 max-md:px-5"
        >
          Save Changes
        </button>
      </div>
    </form>
  );
};

export default ProfileForm;
