/**
 * This code was generated by Builder.io.
 */
import React from "react";

const SocialLinks = () => {
  return (
    <div className="flex gap-6 items-start self-start mt-6">
      <a href="#" aria-label="Facebook">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/30ef1881c8ba382ad841b10dec22c4728e1ac56594cd8fd1b8fc54e4c0c91052?placeholderIfAbsent=true&apiKey=907845159c31450ca87b5b226dbf1f02"
          alt=""
          className="object-contain shrink-0 w-6 aspect-square"
        />
      </a>
      <a href="#" aria-label="Twitter">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/261b4867f26fd96eda2f4aae89489d3141d268d80f3e71a6e9bc022cf30400c4?placeholderIfAbsent=true&apiKey=907845159c31450ca87b5b226dbf1f02"
          alt=""
          className="object-contain shrink-0 w-6 aspect-square"
        />
      </a>
      <a href="#" aria-label="Instagram">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/d0b67f52bb53b8c3b436cfc50867157e647c1cc5fa6f7cc373ba309b35f3d286?placeholderIfAbsent=true&apiKey=907845159c31450ca87b5b226dbf1f02"
          alt=""
          className="object-contain shrink-0 w-6 aspect-square"
        />
      </a>
      <a href="#" aria-label="LinkedIn">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/017f03fd6271e23e94e189db8506f53ec67e53623ecac07e20b0cc0e64aa481c?placeholderIfAbsent=true&apiKey=907845159c31450ca87b5b226dbf1f02"
          alt=""
          className="object-contain shrink-0 w-6 aspect-square"
        />
      </a>
    </div>
  );
};

export default SocialLinks;
