/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Breadcrumb = () => {
  return (
    <nav
      aria-label="Breadcrumb"
      className="flex gap-3 items-center text-sm text-black"
    >
      <a href="#" className="self-stretch my-auto opacity-50">
        Account
      </a>
      <a href="#" className="self-stretch my-auto opacity-50">
        My Account
      </a>
      <a href="#" className="self-stretch my-auto opacity-50">
        Product
      </a>
      <a href="#" className="self-stretch my-auto opacity-50">
        View Cart
      </a>
      <span className="self-stretch my-auto" aria-current="page">
        CheckOut
      </span>
    </nav>
  );
};

export default Breadcrumb;
