/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "../../components/component/Header";
import Navigation from "./Navigation";
import Breadcrumb from "./Breadcrumb";
import BillingForm from "./BillingForm";
import OrderSummary from "./OrderSummary";
import PaymentOptions from "./PaymentOptions";
import CouponForm from "./CouponForm";
import Footer from "./Footer";

const CheckoutPage = () => {
  return (
    <div className="flex flex-col bg-white">
      <Header />
      <div className="" />
      <main className="flex flex-col items-start self-center mt-20 w-full max-w-[1170px] max-md:mt-10 max-md:max-w-full">
        <Breadcrumb />
        <h1 className="mt-20 text-4xl font-medium tracking-widest leading-none text-black max-md:mt-10">
          Billing Details
        </h1>
        <div className="self-stretch mt-12 max-md:mt-10 max-md:max-w-full">
          <div className="flex gap-5 max-md:flex-col">
            <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
              <BillingForm />
            </div>
            <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
              <div className="flex flex-col items-start mt-8 max-md:mt-10 max-md:max-w-full">
                <OrderSummary />
                <div className="flex flex-col mt-8 max-w-full w-[422px]">
                  <div className="flex flex-col w-full">
                    <div className="flex flex-col w-full max-w-[422px] max-md:max-w-full">
                      <div className="flex flex-col w-full max-md:max-w-full">
                        <div className="flex gap-10 items-start text-base text-black whitespace-nowrap max-md:max-w-full">
                          <div>Subtotal:</div>
                          <div>$1750</div>
                        </div>
                        <div className="flex flex-col mt-4 w-full rotate-[8.742277657347563e-8rad]">
                          <div className="z-10 shrink-0 h-px bg-black border border-black border-solid max-md:max-w-full" />
                        </div>
                      </div>
                      <div className="flex gap-10 items-start mt-4 text-base text-black whitespace-nowrap max-md:max-w-full">
                        <div>Shipping:</div>
                        <div>Free</div>
                      </div>
                    </div>
                    <div className="flex flex-col mt-4 w-full rotate-[8.742277657347563e-8rad]">
                      <div className="z-10 shrink-0 h-px bg-black border border-black border-solid max-md:max-w-full" />
                    </div>
                  </div>
                  <div className="flex gap-10 items-start mt-4 text-base text-black whitespace-nowrap max-md:max-w-full">
                    <div>Total:</div>
                    <div>$1750</div>
                  </div>
                </div>
                <PaymentOptions />
                <CouponForm />
                <button className="gap-2.5 self-stretch px-12 py-4 mt-8 text-base font-medium bg-red-500 rounded text-neutral-50 max-md:px-5">
                  Place Order
                </button>
              </div>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default CheckoutPage;
