/**
 * This code was generated by Builder.io.
 */
import React from "react";

const CouponForm = () => {
  return (
    <form className="flex flex-wrap gap-4 items-end self-stretch mt-8 text-base max-md:max-w-full">
      <div className="flex overflow-hidden flex-col justify-center items-start px-6 py-4 text-black rounded border border-black border-solid min-w-[240px] w-[300px] max-md:px-5">
        <label htmlFor="couponCode" className="sr-only">
          Coupon Code
        </label>
        <input
          type="text"
          id="couponCode"
          placeholder="Coupon Code"
          className="w-full bg-transparent border-none outline-none opacity-50"
        />
      </div>
      <button
        type="submit"
        className="gap-2.5 self-stretch px-12 py-4 font-medium bg-red-500 rounded text-neutral-50 max-md:px-5"
      >
        Apply Coupon
      </button>
    </form>
  );
};

export default CouponForm;
