/**
 * This code was generated by Builder.io.
 */
import React from "react";
import NewsletterForm from "./NewsletterForm";
import FooterLinks from "./FooterLinks";
import AppDownload from "./AppDownload";
import SocialLinks from "./SocialLinks";

const Footer = () => {
  return (
    <footer className="flex overflow-hidden flex-col justify-end pt-20 pb-6 mt-36 w-full bg-black max-md:mt-10 max-md:max-w-full">
      <div className="flex flex-wrap gap-10 justify-center items-start self-center max-md:max-w-full">
        <NewsletterForm />
        <FooterLinks
          title="Support"
          items={[
            "111 Bijoy sarani, Dhaka, DH 1515, Bangladesh.",
            "exclusive@gmail.com",
            "+88015-88888-9999",
          ]}
        />
        <FooterLinks
          title="Account"
          items={["My Account", "Login / Register", "Cart", "Wishlist", "Shop"]}
        />
        <FooterLinks
          title="Quick Link"
          items={["Privacy Policy", "Terms Of Use", "FAQ", "Contact"]}
        />
        <AppDownload />
      </div>
      <div className="flex flex-col items-center mt-16 w-full max-md:mt-10 max-md:max-w-full">
        <div className="flex flex-col w-full max-md:max-w-full">
          <div className="w-full bg-white border border-white border-solid opacity-40 min-h-[1px] max-md:max-w-full" />
        </div>
        <div className="flex gap-3 items-center mt-4 text-base text-white">
          <div className="flex gap-1.5 items-center self-stretch my-auto min-w-[240px]">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/e936e113a5282b5434ef099638e1c001097cc1cacb36da2b8991c224b3b3c70b?placeholderIfAbsent=true&apiKey=a7423420d6024871abbabbd8b3aee7fb"
              className="object-contain shrink-0 self-stretch my-auto w-5 aspect-square"
              alt=""
            />
            <div className="self-stretch my-auto">
              Copyright Rimel 2022. All right reserved
            </div>
          </div>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
