/**
 * This code was generated by Builder.io.
 */
import React from "react";

const FooterLinks = ({ title, items }) => {
  return (
    <div className="flex flex-col text-neutral-50">
      <div className="text-xl font-medium leading-snug">{title}</div>
      <div className="flex flex-col mt-6 text-base">
        {items.map((item, index) => (
          <div key={index} className={index > 0 ? "mt-4" : ""}>
            {item}
          </div>
        ))}
      </div>
    </div>
  );
};

export default FooterLinks;
