/**
 * This code was generated by Builder.io.
 */
import React from "react";
import LanguageSelector from "./LanguageSelector";

const Header = () => {
  return (
    <header className="flex overflow-hidden flex-col justify-center items-end px-16 py-3 w-full text-sm bg-black text-neutral-50 max-md:px-5 max-md:max-w-full">
      <div className="flex justify-between items-center px-8 py-3 w-full text-sm bg-black text-neutral-50 max-md:px-5 max-md:max-w-full
      ">
        <div className="flex flex-wrap gap-2 items-center min-w-[240px] max-md:max-w-full">
          <div className="self-stretch my-auto w-[474px] max-md:max-w-full">
            Summer Sale For All Swim Suits And Free Express Delivery - OFF 50%!
          </div>
          <a
            href="#"
            className="self-stretch my-auto font-semibold leading-6 text-center underline"
          >
            ShopNow
          </a>
        </div>
        <LanguageSelector />
      </div>
    </header>
  );
};

export default Header;
