/**
 * This code was generated by Builder.io.
 */
import React from "react";

const LanguageSelector = () => {
  return (
    <div className="flex gap-1.5 justify-center items-center whitespace-nowrap">
      <div className="self-stretch my-auto">English</div>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/8c458026ddcb4daaaca9291897ab1b8ab8e65bd1233e48db8bbc95eb90ee3e16?placeholderIfAbsent=true&apiKey=a7423420d6024871abbabbd8b3aee7fb"
        className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
        alt=""
      />
    </div>
  );
};

export default LanguageSelector;
