/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SearchBar from "./SearchBar";

const Navigation = () => {
  return (
    <nav className="flex flex-wrap gap-10 items-center self-center mt-10 max-md:max-w-full">
      <div className="flex flex-wrap gap-10 items-start self-stretch my-auto text-black min-w-[240px] max-md:max-w-full">
        <div className="text-2xl font-bold tracking-wider leading-none whitespace-nowrap w-[118px]">
          Exclusive
        </div>
        <div className="flex gap-10 items-start text-base text-center min-w-[240px]">
          <a href="#" className="w-12 whitespace-nowrap">
            Home
          </a>
          <a href="#" className="whitespace-nowrap w-[66px]">
            Contact
          </a>
          <a href="#" className="w-12 whitespace-nowrap">
            About
          </a>
          <a href="#" className="w-[61px]">
            Sign Up
          </a>
        </div>
      </div>
      <div className="flex gap-6 items-center self-stretch my-auto min-w-[240px]">
        <SearchBar />
        <div className="flex gap-4 justify-center items-center self-stretch my-auto">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/2f46b01d8f56846dabad72a61fd444f3085a8b624cfad99f0b703fb6b78182f5?placeholderIfAbsent=true&apiKey=a7423420d6024871abbabbd8b3aee7fb"
            className="object-contain shrink-0 self-stretch my-auto w-8 aspect-square"
            alt="Wishlist"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/1d49936bb7e7947951a24074df0be75fc667e72893b1780ac9e82c006a87816b?placeholderIfAbsent=true&apiKey=a7423420d6024871abbabbd8b3aee7fb"
            className="object-contain shrink-0 self-stretch my-auto w-8 aspect-square"
            alt="Cart"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/505a01368e57ac667ecd551fd161eb3fa8202cee72841e5b11d9f712055e4607?placeholderIfAbsent=true&apiKey=a7423420d6024871abbabbd8b3aee7fb"
            className="object-contain shrink-0 self-stretch my-auto w-8 aspect-square"
            alt="User profile"
          />
        </div>
      </div>
    </nav>
  );
};

export default Navigation;
