/**
 * This code was generated by Builder.io.
 */
import React from "react";

const OrderSummary = () => {
  const orderItems = [
    {
      name: "LCD Monitor",
      price: 650,
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/d9756deeacadef6fc2b2413c9b933bb26e53650502fc030bf17d33ac0ca9c50b?placeholderIfAbsent=true&apiKey=a7423420d6024871abbabbd8b3aee7fb",
    },
    {
      name: "H1 Gamepad",
      price: 1100,
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/c14a91db632bf827e69ef9e777343ed6de5d2c8c8c686130a56a4c6519bc144c?placeholderIfAbsent=true&apiKey=a7423420d6024871abbabbd8b3aee7fb",
    },
  ];

  return (
    <div className="flex flex-col items-end text-base max-md:max-w-full">
      {orderItems.map((item, index) => (
        <div
          key={index}
          className="flex gap-6 items-center max-md:max-w-full mt-8"
        >
          <img
            loading="lazy"
            src={item.image}
            className="object-contain shrink-0 self-stretch my-auto aspect-square w-[54px]"
            alt={item.name}
          />
          <div className="flex gap-10 items-center self-stretch my-auto min-w-[240px]">
            <div className="self-stretch my-auto text-black">{item.name}</div>
            <div className="self-stretch my-auto text-black">${item.price}</div>
          </div>
        </div>
      ))}
    </div>
  );
};

export default OrderSummary;
