/**
 * This code was generated by Builder.io.
 */
import React from "react";

const SearchBar = () => {
  return (
    <form className="flex flex-col justify-center items-center self-stretch py-2 pr-3 pl-5 my-auto text-xs text-black rounded bg-neutral-100 min-w-[240px]">
      <div className="flex gap-9 justify-center items-center">
        <label htmlFor="search" className="sr-only">
          What are you looking for?
        </label>
        <input
          type="search"
          id="search"
          placeholder="What are you looking for?"
          className="self-stretch my-auto bg-transparent border-none outline-none opacity-50"
        />
        <button type="submit" aria-label="Search">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/7a36546edd30f9649053810fdbf6c98d92541e863e7b8b10ab13af855343b34e?placeholderIfAbsent=true&apiKey=a7423420d6024871abbabbd8b3aee7fb"
            className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
            alt=""
          />
        </button>
      </div>
    </form>
  );
};

export default SearchBar;
