/**
 * This code was generated by Builder.io.
 */
import React from "react";

function FooterLinks() {
  const linkGroups = [
    {
      title: "Support",
      links: [
        { text: "111 Bijoy sarani, Dhaka, DH 1515, Bangladesh.", href: "#" },
        { text: "exclusive@gmail.com", href: "mailto:exclusive@gmail.com" },
        { text: "+88015-88888-9999", href: "tel:+8801588888999" },
      ],
    },
    {
      title: "Account",
      links: [
        { text: "My Account", href: "#" },
        { text: "Login / Register", href: "#" },
        { text: "Cart", href: "#" },
        { text: "Wishlist", href: "#" },
        { text: "Shop", href: "#" },
      ],
    },
    {
      title: "Quick Link",
      links: [
        { text: "Privacy Policy", href: "#" },
        { text: "Terms Of Use", href: "#" },
        { text: "FAQ", href: "#" },
        { text: "Contact", href: "#" },
      ],
    },
  ];

  return (
    <>
      {linkGroups.map((group, index) => (
        <div key={index} className="flex flex-col text-neutral-50">
          <h3 className="text-xl font-medium leading-snug">{group.title}</h3>
          <ul className="flex flex-col mt-6 text-base">
            {group.links.map((link, linkIndex) => (
              <li key={linkIndex} className={linkIndex > 0 ? "mt-4" : ""}>
                <a href={link.href}>{link.text}</a>
              </li>
            ))}
          </ul>
        </div>
      ))}
    </>
  );
}

export default FooterLinks;
