/**
 * This code was generated by Builder.io.
 */
import React from "react";
import LanguageSelector from "./LanguageSelector";
import SearchBar from "./SearchBar";
import IconGroup from "./IconGroup";

function Header() {
  return (
    <header className="flex flex-col bg-white">
      <div className="flex overflow-hidden flex-col justify-center items-end px-16 py-3 w-full text-sm bg-black text-neutral-50 max-md:px-5 max-md:max-w-full">
        <div className="flex flex-wrap gap-10 items-start max-md:max-w-full">
          <div className="flex flex-wrap gap-2 items-center min-w-[240px] max-md:max-w-full">
            <div className="self-stretch my-auto w-[474px] max-md:max-w-full">
              Summer Sale For All Swim Suits And Free Express Delivery - OFF
              50%!
            </div>
            <a
              href="#"
              className="self-stretch my-auto font-semibold leading-6 text-center underline"
            >
              ShopNow
            </a>
          </div>
          <LanguageSelector />
        </div>
      </div>
      <nav className="flex flex-wrap gap-10 items-center self-center mt-10 max-md:max-w-full">
        <div className="flex flex-wrap gap-10 items-start self-stretch my-auto text-black min-w-[240px] max-md:max-w-full">
          <h1 className="text-2xl font-bold tracking-wider leading-none whitespace-nowrap w-[118px]">
            Exclusive
          </h1>
          <ul className="flex gap-10 items-start text-base text-center min-w-[240px]">
            <li>
              <a href="#" className="w-12 whitespace-nowrap">
                Home
              </a>
            </li>
            <li>
              <a href="#" className="whitespace-nowrap w-[66px]">
                Contact
              </a>
            </li>
            <li>
              <a href="#" className="w-12 whitespace-nowrap">
                About
              </a>
            </li>
            <li>
              <a href="#" className="w-[61px]">
                Sign Up
              </a>
            </li>
          </ul>
        </div>
        <div className="flex gap-6 items-center self-stretch my-auto min-w-[240px]">
          <SearchBar />
          <IconGroup />
        </div>
      </nav>
      <div className="mt-4 w-full bg-black border border-black border-solid opacity-30 min-h-[1px] max-md:max-w-full" />
    </header>
  );
}

export default Header;
