/**
 * This code was generated by Builder.io.
 */
import React from "react";

function IconGroup() {
  const icons = [
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/850597cc14d3bfef027aa097fc5bca3ac1b650d683dc1d3c8c0134d5cd9a061d?placeholderIfAbsent=true&apiKey=f647c9309a8f4fd282df2349ecee336e",
      alt: "Wishlist",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/27e6583cc2b0ad6384fa0e09ba54d132ea13906a2c9553ea3ae9481ef2628ff7?placeholderIfAbsent=true&apiKey=f647c9309a8f4fd282df2349ecee336e",
      alt: "Cart",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/505a01368e57ac667ecd551fd161eb3fa8202cee72841e5b11d9f712055e4607?placeholderIfAbsent=true&apiKey=f647c9309a8f4fd282df2349ecee336e",
      alt: "User account",
    },
  ];

  return (
    <div className="flex gap-4 justify-center items-center self-stretch my-auto">
      {icons.map((icon, index) => (
        <button key={index} aria-label={icon.alt}>
          <img
            loading="lazy"
            src={icon.src}
            className="object-contain shrink-0 self-stretch my-auto w-8 aspect-square"
            alt=""
          />
        </button>
      ))}
    </div>
  );
}

export default IconGroup;
