/**
 * This code was generated by Builder.io.
 */
import React from "react";

function ProductGallery({images}) {

  return (
    <div className="flex flex-col w-[64%] max-md:ml-0 max-md:w-full">
      <div className="grow max-md:mt-10 max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          <div className="flex flex-col w-3/12 max-md:ml-0 max-md:w-full">
            <div className="flex flex-col grow max-md:mt-8">
              {images.map((image, index) => (
                <div
                  key={index}
                  className={`flex overflow-hidden flex-col justify-center px-6 py-3 ${
                    index > 0 ? "mt-4" : ""
                  } rounded bg-neutral-100 max-md:px-5`}
                >
                  <img
                    loading="lazy"
                    src={image.src}
                    className="object-contain aspect-[1.06] w-[121px]"
                    alt={image.alt}
                  />
                </div>
              ))}
            </div>
          </div>
          <div className="flex flex-col ml-5 w-9/12 max-md:ml-0 max-md:w-full">
            <div className="flex overflow-hidden flex-col grow justify-center px-7 py-36 w-full rounded bg-neutral-100 max-md:px-5 max-md:py-24 max-md:mt-8 max-md:max-w-full">
              <img
                loading="lazy"
                src={images[0]}
                className="object-contain w-full aspect-[1.42] max-md:max-w-full"
                alt="Main product image"
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default ProductGallery;
