/**
 * This code was generated by Builder.io.
 */
import React from "react";

function ProductGallery() {
  const thumbnails = [
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/5ff58a315ae76c092e4308f9e1dd636e14dff898d550453232b2df9619740c99?placeholderIfAbsent=true&apiKey=f647c9309a8f4fd282df2349ecee336e",
      alt: "Product thumbnail 1",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/846b04a32465038d31c7eebb8207360b937f24ee6e001125f678465a5dae8af0?placeholderIfAbsent=true&apiKey=f647c9309a8f4fd282df2349ecee336e",
      alt: "Product thumbnail 2",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/bfe5f7ca2fb1b090aaa31900efe3fded42ca5586c5dea7a3fc44e288ab7aa6b5?placeholderIfAbsent=true&apiKey=f647c9309a8f4fd282df2349ecee336e",
      alt: "Product thumbnail 3",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/362103a03f54be471e065d362aafa804ca7e4c2406a09fd960d3ef8a81cc4e0c?placeholderIfAbsent=true&apiKey=f647c9309a8f4fd282df2349ecee336e",
      alt: "Product thumbnail 4",
    },
  ];

  return (
    <div className="flex flex-col w-[64%] max-md:ml-0 max-md:w-full">
      <div className="grow max-md:mt-10 max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          <div className="flex flex-col w-3/12 max-md:ml-0 max-md:w-full">
            <div className="flex flex-col grow max-md:mt-8">
              {thumbnails.map((thumbnail, index) => (
                <div
                  key={index}
                  className={`flex overflow-hidden flex-col justify-center px-6 py-3 ${
                    index > 0 ? "mt-4" : ""
                  } rounded bg-neutral-100 max-md:px-5`}
                >
                  <img
                    loading="lazy"
                    src={thumbnail.src}
                    className="object-contain aspect-[1.06] w-[121px]"
                    alt={thumbnail.alt}
                  />
                </div>
              ))}
            </div>
          </div>
          <div className="flex flex-col ml-5 w-9/12 max-md:ml-0 max-md:w-full">
            <div className="flex overflow-hidden flex-col grow justify-center px-7 py-36 w-full rounded bg-neutral-100 max-md:px-5 max-md:py-24 max-md:mt-8 max-md:max-w-full">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/2e0fb45ef738ddce3471cc209033d00d2fe1bea6dc52358f55df055db788b713?placeholderIfAbsent=true&apiKey=f647c9309a8f4fd282df2349ecee336e"
                className="object-contain w-full aspect-[1.42] max-md:max-w-full"
                alt="Main product image"
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default ProductGallery;
