/**
 * This code was generated by Builder.io.
 */
"use client";
import React, { useEffect, useState } from "react";
import Header from "../../components/component/Header";
import ProductDetails from "./ProductDetails";
import RelatedProducts from "./RelatedProducts";
import Footer from "./Footer";
import ProductId from "../../api/buyer";
import { useSearchParams } from 'next/navigation'

function ProductPage() {
  const [productData, setProductData] = useState(null);
  const [productId, setProductId] = useState(null);

  const fallbackImage =
  "https://via.placeholder.com/150";

  useEffect(() => {
     // Lấy id từ URL
    const urlParams = new URLSearchParams(window.location.search);
    const id = urlParams.get('id');
    setProductId(id)

    const fetchProductById = async () => {
      if (!id) return; 

      try {
        const response = await ProductId.product.getProductById(id); 
        console.log("Response Status Code:", response);
        
        if (response.statusCode === 200) {
          setProductData(response.data);
          console.log("Product fetched:", response.data);
        } else {
          console.error("Failed to fetch product details");
        }
      } catch (error) {
        console.error("Error fetching product details:", error);
      }
    };
  
    if (id) {
      fetchProductById();  // Chỉ fetch khi có productId
    }
  }, []);
  
  if (!productData) {
    return <div>Loading...</div>; // Hiển thị loading khi chưa có dữ liệu
  }

  return (
    <div className="flex overflow-hidden flex-col bg-white">
      <Header />
      <div className="flex justify-center items-center flex-1">
        <main>
          <ProductDetails productData={productData}/>
          <RelatedProducts />
        </main>
      </div>
      <Footer />
    </div>
  );
}

export default ProductPage;
