/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import ProductDetails from "./ProductDetails";
import RelatedProducts from "./RelatedProducts";
import Footer from "./Footer";

function ProductPage() {
  return (
    <div className="flex overflow-hidden flex-col bg-white">
      <Header />
      <div className="flex justify-center items-center flex-1">
        <main>
          <ProductDetails />
          <RelatedProducts />
        </main>
      </div>
      <Footer />
    </div>
  );
}

export default ProductPage;
