/**
 * This code was generated by Builder.io.
 */
import React from "react";

function QuantitySelector() {
  return (
    <div className="flex items-center gap-0 text-xl leading-snug text-black whitespace-nowrap min-h-[44px]">
      <button
        aria-label="Decrease quantity"
        className="w-10 h-11 flex items-center justify-center border border-black border-opacity-50 rounded-l hover:bg-gray-200"
      >
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/ed9ed51dc91da1a317a6ec57e005b4e5f8a1b0bff1721c29819dbbc2af1e9ae3?placeholderIfAbsent=true&apiKey=f647c9309a8f4fd282df2349ecee336e"
          className="object-contain w-6 h-6"
          alt="Decrease"
        />
      </button>
      <div className="px-5 py-2 w-16 border-t border-b border-black border-opacity-50 flex items-center justify-center">
        2
      </div>
      <button
        aria-label="Increase quantity"
        className="w-10 h-11 flex items-center justify-center border border-black border-opacity-50 rounded-r hover:bg-gray-200"
      >
        <img
          loading="lazy"
          src="https://png.pngtree.com/element_our/20190531/ourmid/pngtree-shopping-cart-convenient-icon-image_1287807.jpg"
          className="object-contain w-6 h-6"
          alt="Increase"
        />
      </button>
    </div>
  );
}

export default QuantitySelector;
