/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ProductCard from "./ProductCard";

function RelatedProducts() {
  

  return (
    <section className="flex flex-col mt-36 max-md:mt-10 max-md:max-w-full">
      <div className="flex gap-4 items-center self-start">
        <div className="flex flex-col self-stretch my-auto w-5">
          <div className="flex shrink-0 h-10 bg-red-500 rounded" />
        </div>
        <h2 className="self-stretch my-auto text-base font-semibold leading-none text-red-500">
          Related Item
        </h2>
      </div>
      <div className="flex flex-wrap gap-8 items-start mt-16 max-md:mt-10 max-md:max-w-full">
        {products.map((product, index) => (
          <ProductCard key={index} {...product} />
        ))}
      </div>
    </section>
  );
}

export default RelatedProducts;
