/**
 * This code was generated by Builder.io.
 */
import React from "react";

function AppDownload() {
  return (
    <div className="flex flex-col">
      <h3 className="text-xl font-medium leading-snug text-neutral-50">
        Download App
      </h3>
      <div className="flex flex-col mt-6">
        <p className="text-xs font-medium opacity-70 text-neutral-50">
          Save $3 with App New User Only
        </p>
        <div className="flex gap-2 items-center mt-2">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/318eab6f820c56237ca220bfa13661aea13cd54a84302eb7e0150453eee7de84?placeholderIfAbsent=true&apiKey=f647c9309a8f4fd282df2349ecee336e"
            className="object-contain shrink-0 self-stretch my-auto w-20 aspect-square"
            alt="QR Code"
          />
          <div className="flex flex-col self-stretch my-auto w-[110px]">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/9609d84ff6b2a48f066237aa51e46748f10363b2a68201878dd128a06adfe6df?placeholderIfAbsent=true&apiKey=f647c9309a8f4fd282df2349ecee336e"
              className="object-contain max-w-full aspect-[2.75] w-[110px]"
              alt="Download on App Store"
            />
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/c3712826c87e4dff101cdacecb5b28e00fe08e16a137f394134f0f1f4cdf00fe?placeholderIfAbsent=true&apiKey=f647c9309a8f4fd282df2349ecee336e"
              className="object-contain mt-1 max-w-full aspect-[2.75] w-[110px]"
              alt="Get it on Google Play"
            />
          </div>
        </div>
      </div>
    </div>
  );
}

export default AppDownload;
