/**
 * This code was generated by Builder.io.
 */

import React, {useState} from "react";
import {Input} from "../../components/ui/Input"
import { useRouter } from "next/navigation";
import { signIn } from "next-auth/react";


const LoginForm = () => {

  const [formData, setFormData] = useState({
    email: '',
    password: '',
  });

  const router = useRouter();


  const onSubmit = async (e) => {
    e.preventDefault();
    const email = e.target.email.value;
    const password = e.target.password.value;
    const data = await signIn("credentials", {email, password, redirect: false});
  };

  return (
    <>
      <section className="flex flex-col self-stretch my-auto min-w-[240px]">
      <div className="flex flex-col max-w-full w-[370px]">
        <div className="flex flex-col self-start text-black">
          <h2 className="text-4xl font-medium tracking-widest leading-none">
            Log in to Exclusive
          </h2>
          <p className="mt-6 text-base">Enter your details below</p>
        </div>
        <form onSubmit={onSubmit} className="flex flex-col mt-12 w-full max-md:mt-10">
          <div className="flex flex-col w-full">
            <label
              htmlFor="emailOrPhone"
              className="text-base text-black opacity-40"
            >
              Email or Phone Number
            </label>
            <Input
              type="text"
              id="email"
              className="mt-2 border-b border-black"
              required
            />
          </div>
          <div className="flex flex-col mt-10 w-full">
            <label
              htmlFor="password"
              className="text-base text-black opacity-40"
            >
              Password
            </label>
            <Input
              type="password"
              id="password"
              className="mt-2 border-b border-black"
              required
            />
          </div>
          <div className="flex gap-10 items-center mt-10 text-base">
            <button
              type="submit"
              className="flex-col self-stretch my-auto font-medium text-neutral-50 gap-2.5 px-12 py-4 bg-red-500 rounded max-md:px-5"
            >
              Log In
            </button>
            <a href="#" className="self-stretch my-auto text-red-500">
              Forget Password?
            </a>
          </div>
        </form>
      </div>
    </section>  
    </>
  );
}

export default LoginForm;
