/**
 * This code was generated by Builder.io.
 */
"use client"
import React from "react";
import Header from "../../components/component/Header";
import MainContent from "./MainContent";
import Footer from "./Footer";

function LoginPage() {
  return (
    <div className="flex overflow-hidden flex-col bg-white">
      <Header />
      <div className="" />
      <MainContent />
      <Footer />
    </div>
  );
}

export default LoginPage;
