/**
 * This code was generated by Builder.io.
 */

import React, {useState} from "react";
import {Input} from "../../components/ui/input"
import { useRouter } from "next/navigation";
import { signIn } from "next-auth/react";
import {showSuccessAlert, showErrorAlert} from "../../utils/reactSweetAlert"
import {Button} from "../../components/ui/button"
const LoginForm = () => {

  const [formData, setFormData] = useState({
    email: '',
    password: '',
  });
  const [userId, setUserId] = useState(null);

  const router = useRouter();


  const onSubmit = async (e) => {
    e.preventDefault();
    const email = e.target.email.value;
    const password = e.target.password.value;
    const data = await signIn("credentials", {email, password, redirect: false});

    if (data.error) {
      showErrorAlert("Đăng nhập thất bại","sai tên tài khoản hoặc mật khẩu")
    }else{
      router.push("/login");
    }

  };

  const handleGoogleSignIn = async () => {
    const data = await signIn("google",{redirect: false});
    console.log(data);
  };

  return (
    <>
      <section className="flex flex-col self-stretch my-auto min-w-[240px]">
      <div className="flex flex-col max-w-full w-[370px]">
        <div className="flex flex-col self-start text-black">
          <h2 className="text-4xl font-medium tracking-widest leading-none">
            Log in to Exclusive
          </h2>
          <p className="mt-6 text-base">Enter your details below</p>
        </div>
        <form onSubmit={onSubmit} className="flex flex-col mt-12 w-full max-md:mt-10">
          <div className="flex flex-col w-full">
            <label
              htmlFor="emailOrPhone"
              className="text-base text-black opacity-40"
            >
              Email or Phone Number
            </label>
            <Input
              type="text"
              id="email"
              className="mt-2 border-b border-black"
              required
            />
          </div>
          <div className="flex flex-col mt-10 w-full">
            <label
              htmlFor="password"
              className="text-base text-black opacity-40"
            >
              Password
            </label>
            <Input
              type="password"
              id="password"
              className="mt-2 border-b border-black"
              
            />
          </div>
          <div className="flex gap-10 items-center mt-10 text-base">
            <button
              type="submit"
              className="flex-col self-stretch my-auto font-medium text-neutral-50 gap-2.5 px-12 py-4 bg-red-500 rounded max-md:px-5"
            >
              Log In
            </button>
            
            <a href="#" className="self-stretch my-auto text-red-500">
              Forget Password?
            </a>
            
          </div>
        </form>
        <div className="mt-12">
          <Button
              onClick={handleGoogleSignIn}
              variant="outline"
              className="w-full bg-white text-gray-900 hover:bg-gray-100 focus:ring-4 focus:ring-[#4285F4]/50 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center justify-center dark:focus:ring-[#4285F4]/55 mr-2 mb-2"
            >
              <svg
                className="mr-2 -ml-1 w-4 h-4"
                aria-hidden="true"
                focusable="false"
                data-prefix="fab"
                data-icon="google"
                role="img"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 488 512"
              >
                <path
                  fill="currentColor"
                  d="M488 261.8C488 403.3 391.1 504 248 504 110.8 504 0 393.2 0 256S110.8 8 248 8c66.8 0 123 24.5 166.3 64.9l-67.5 64.9C258.5 52.6 94.3 116.6 94.3 256c0 86.5 69.1 156.6 153.7 156.6 98.2 0 135-70.4 140.8-106.9H248v-85.3h236.1c2.3 12.7 3.9 24.9 3.9 41.4z"
                ></path>
              </svg>
              Sign in with Google
            </Button>
        </div>
      </div>
    </section>  
    </>
  );
}

export default LoginForm;



