/**
 * This code was generated by Builder.io.
 */
import React from "react";
import LoginForm from "./LoginForm";
import LoginForm2 from "./LoginForm2";

function MainContent() {
  return (
    <>
      <div className="flex justify-center">
      <main className="flex flex-wrap gap-10 items-center self-start mt-14 max-md:mt-10 max-md:max-w-full">
      {/* <div className="flex overflow-hidden flex-col self-stretch pt-20 my-auto rounded-none bg-slate-300 min-w-[240px] w-[805px] max-md:max-w-full">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/526332f3654bee831fd7f748e7fb8c42f7791287d3c693c7c404e5e89af239aa?placeholderIfAbsent=true&apiKey=f647c9309a8f4fd282df2349ecee336e"
          className="object-contain w-full aspect-[1.14] max-md:max-w-full"
          alt="Product showcase"
        />
      </div> */}
      <div className="flex ">
        <LoginForm2 />
      </div>
    </main>
    </div>
    </>
  );
}

export default MainContent;
