/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SearchBar from "./SearchBar";

function Navigation() {
  const navItems = ["Home", "Contact", "About", "Sign Up"];

  return (
    <nav className="flex flex-wrap gap-10 items-center self-center mt-10 text-black max-md:max-w-full">
      <div className="flex flex-wrap gap-10 items-start self-stretch my-auto min-w-[240px] max-md:max-w-full">
        <h1 className="text-2xl font-bold tracking-wider leading-none whitespace-nowrap w-[118px]">
          Exclusive
        </h1>
        <ul className="flex gap-10 items-start text-base text-center min-w-[240px]">
          {navItems.map((item, index) => (
            <li
              key={index}
              className={`whitespace-nowrap ${
                item === "Sign Up" ? "w-[61px]" : "w-12"
              }`}
            >
              <a href="#">{item}</a>
            </li>
          ))}
        </ul>
      </div>
      <SearchBar />
    </nav>
  );
}

export default Navigation;
