/**
 * This code was generated by Builder.io.
 */
import React from "react";

function SocialIcons() {
  const socialIcons = [
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/30ef1881c8ba382ad841b10dec22c4728e1ac56594cd8fd1b8fc54e4c0c91052?placeholderIfAbsent=true&apiKey=f647c9309a8f4fd282df2349ecee336e",
      alt: "Facebook",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/ee8e3628bbf814a4db6d119193495a6d0ba420eed1b29b7f14d7f94c9ac9bc79?placeholderIfAbsent=true&apiKey=f647c9309a8f4fd282df2349ecee336e",
      alt: "Twitter",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/d0b67f52bb53b8c3b436cfc50867157e647c1cc5fa6f7cc373ba309b35f3d286?placeholderIfAbsent=true&apiKey=f647c9309a8f4fd282df2349ecee336e",
      alt: "Instagram",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/017f03fd6271e23e94e189db8506f53ec67e53623ecac07e20b0cc0e64aa481c?placeholderIfAbsent=true&apiKey=f647c9309a8f4fd282df2349ecee336e",
      alt: "LinkedIn",
    },
  ];

  return (
    <div className="flex gap-6 items-start self-start mt-6">
      {socialIcons.map((icon, index) => (
        <a href="#" key={index} aria-label={icon.alt}>
          <img
            loading="lazy"
            src={icon.src}
            className="object-contain shrink-0 w-6 aspect-square"
            alt=""
          />
        </a>
      ))}
    </div>
  );
}

export default SocialIcons;
