/**
 * This code was generated by Builder.io.
 */
import React from "react";

const features = [
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/056d5a5d5ce0a443a4eee7a6ceeda3264b0a7c57b0b1fbe4f42dc0178a91c01c?placeholderIfAbsent=true&apiKey=a7423420d6024871abbabbd8b3aee7fb",
    title: "FREE AND FAST DELIVERY",
    description: "Free delivery for all orders over $140",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/cf1200c20e58b367857beb90de6d5503f85625eae58410ce4d357553f480ddb0?placeholderIfAbsent=true&apiKey=a7423420d6024871abbabbd8b3aee7fb",
    title: "24/7 CUSTOMER SERVICE",
    description: "Friendly 24/7 customer support",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/7f7d72e7f12212fabf73ce7a0ace2ba3bec407aed1f0b8938db682544265449b?placeholderIfAbsent=true&apiKey=a7423420d6024871abbabbd8b3aee7fb",
    title: "MONEY BACK GUARANTEE",
    description: "We return money within 30 days",
  },
];

const   Features = () => {
  return (
    <section className="flex flex-wrap gap-10 justify-center items-center self-center mt-36 text-black max-md:mt-10 max-md:max-w-full">
      {features.map((feature, index) => (
        <div
          key={index}
          className="flex flex-col items-center self-stretch my-auto min-w-[240px] w-[262px]"
        >
          <img
            loading="lazy"
            src={feature.icon}
            alt=""
            className="object-contain w-20 aspect-square"
          />
          <div className="flex flex-col items-center mt-6">
            <h3 className="text-xl font-semibold leading-snug text-center">
              {feature.title}
            </h3>
            <p className="mt-2 text-sm text-center">{feature.description}</p>
          </div>
        </div>
      ))}
    </section>
  );
};

export default Features;
