/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Footer = () => {
  return (
    <footer className="flex overflow-hidden flex-col justify-end pt-20 pb-6 mt-8 w-full bg-black max-md:max-w-full">
      <div className="flex flex-wrap gap-10 justify-center items-start self-center max-md:max-w-full">
        <div className="flex flex-col text-neutral-50 w-[217px]">
          <div className="flex flex-col self-start">
            <div className="flex flex-col max-w-full whitespace-nowrap w-[118px]">
              <h2 className="w-full text-2xl font-bold tracking-wider leading-none">
                Exclusive
              </h2>
              <h3 className="mt-6 text-xl font-medium leading-snug">
                Subscribe
              </h3>
            </div>
            <p className="mt-6 text-base">Get 10% off your first order</p>
          </div>
          <form className="flex gap-8 items-center py-3 pl-4 mt-4 max-w-full text-base rounded border-solid border-[1.5px] border-neutral-50 w-[217px]">
            <label htmlFor="email-input" className="sr-only">
              Enter your email
            </label>
            <input
              type="email"
              id="email-input"
              placeholder="Enter your email"
              className="self-stretch my-auto bg-transparent border-none outline-none text-neutral-50 placeholder-neutral-50 placeholder-opacity-40"
            />
            <button type="submit" aria-label="Subscribe">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/12a54082781a806227ade42d81d6722495cd51ed50c28a6b5eebf5a1f9d88295?placeholderIfAbsent=true&apiKey=a7423420d6024871abbabbd8b3aee7fb"
                alt=""
                className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
              />
            </button>
          </form>
        </div>
        <div className="flex flex-col text-neutral-50 w-[175px]">
          <h3 className="text-xl font-medium leading-snug">Support</h3>
          <address className="flex flex-col mt-6 max-w-full text-base w-[175px] not-italic">
            <p className="leading-6">
              111 Bijoy sarani, Dhaka, DH 1515, Bangladesh.
            </p>
            <a href="mailto:exclusive@gmail.com" className="mt-4">
              exclusive@gmail.com
            </a>
            <a href="tel:+88015-88888-9999" className="mt-4">
              +88015-88888-9999
            </a>
          </address>
        </div>
        <nav className="flex flex-col text-neutral-50">
          <h3 className="text-xl font-medium leading-snug">Account</h3>
          <ul className="flex flex-col mt-6 text-base">
            <li>
              <a href="/account" className="hover:underline">
                My Account
              </a>
            </li>
            <li>
              <a href="/login" className="mt-4 hover:underline">
                Login / Register
              </a>
            </li>
            <li>
              <a href="/cart" className="mt-4 hover:underline">
                Cart
              </a>
            </li>
            <li>
              <a href="/wishlist" className="mt-4 hover:underline">
                Wishlist
              </a>
            </li>
            <li>
              <a href="/shop" className="mt-4 hover:underline">
                Shop
              </a>
            </li>
          </ul>
        </nav>
        <nav className="flex flex-col text-neutral-50">
          <h3 className="text-xl font-medium leading-snug">Quick Link</h3>
          <ul className="flex flex-col mt-6 text-base">
            <li>
              <a href="/privacy-policy" className="hover:underline">
                Privacy Policy
              </a>
            </li>
            <li>
              <a href="/terms" className="mt-4 hover:underline">
                Terms Of Use
              </a>
            </li>
            <li>
              <a href="/faq" className="mt-4 hover:underline">
                FAQ
              </a>
            </li>
            <li>
              <a href="/contact" className="mt-4 hover:underline">
                Contact
              </a>
            </li>
          </ul>
        </nav>
        <div className="flex flex-col">
          <div className="flex flex-col">
            <h3 className="text-xl font-medium leading-snug text-neutral-50">
              Download App
            </h3>
            <div className="flex flex-col mt-6">
              <p className="text-xs font-medium opacity-70 text-neutral-50">
                Save $3 with App New User Only
              </p>
              <div className="flex gap-2 items-center mt-2">
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/318eab6f820c56237ca220bfa13661aea13cd54a84302eb7e0150453eee7de84?placeholderIfAbsent=true&apiKey=a7423420d6024871abbabbd8b3aee7fb"
                  alt="QR Code"
                  className="object-contain shrink-0 self-stretch my-auto w-20 aspect-square"
                />
                <div className="flex flex-col self-stretch my-auto w-[110px]">
                  <a href="#" aria-label="Download on Google Play">
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/9609d84ff6b2a48f066237aa51e46748f10363b2a68201878dd128a06adfe6df?placeholderIfAbsent=true&apiKey=a7423420d6024871abbabbd8b3aee7fb"
                      alt="Google Play"
                      className="object-contain max-w-full aspect-[2.75] w-[110px]"
                    />
                  </a>
                  <a href="#" aria-label="Download on App Store">
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/c3712826c87e4dff101cdacecb5b28e00fe08e16a137f394134f0f1f4cdf00fe?placeholderIfAbsent=true&apiKey=a7423420d6024871abbabbd8b3aee7fb"
                      alt="App Store"
                      className="object-contain mt-1 max-w-full aspect-[2.75] w-[110px]"
                    />
                  </a>
                </div>
              </div>
            </div>
          </div>
          <div className="flex gap-6 items-start self-start mt-6">
            <a href="#" aria-label="Facebook">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/30ef1881c8ba382ad841b10dec22c4728e1ac56594cd8fd1b8fc54e4c0c91052?placeholderIfAbsent=true&apiKey=a7423420d6024871abbabbd8b3aee7fb"
                alt=""
                className="object-contain shrink-0 w-6 aspect-square"
              />
            </a>
            <a href="#" aria-label="Twitter">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/d99f64ce976ec118e6c3b974e255d577bcae28a4e42169b8366ce8a8a7d644b7?placeholderIfAbsent=true&apiKey=a7423420d6024871abbabbd8b3aee7fb"
                alt=""
                className="object-contain shrink-0 w-6 aspect-square"
              />
            </a>
            <a href="#" aria-label="Instagram">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/d0b67f52bb53b8c3b436cfc50867157e647c1cc5fa6f7cc373ba309b35f3d286?placeholderIfAbsent=true&apiKey=a7423420d6024871abbabbd8b3aee7fb"
                alt=""
                className="object-contain shrink-0 w-6 aspect-square"
              />
            </a>
            <a href="#" aria-label="LinkedIn">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/017f03fd6271e23e94e189db8506f53ec67e53623ecac07e20b0cc0e64aa481c?placeholderIfAbsent=true&apiKey=a7423420d6024871abbabbd8b3aee7fb"
                alt=""
                className="object-contain shrink-0 w-6 aspect-square"
              />
            </a>
          </div>
        </div>
      </div>
      <div className="flex flex-col items-center mt-16 w-full max-md:mt-10 max-md:max-w-full">
        <div className="flex flex-col w-full max-md:max-w-full">
          <div className="w-full bg-white border border-white border-solid opacity-40 min-h-[1px] max-md:max-w-full" />
        </div>
        <div className="flex gap-3 items-center mt-4 text-base text-white">
          <div className="flex gap-1.5 items-center self-stretch my-auto min-w-[240px]">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/d9e77ca5f6362e8c84e9e430400b10a2e9fcc4f4b98d11736abbf6c72292338e?placeholderIfAbsent=true&apiKey=a7423420d6024871abbabbd8b3aee7fb"
              alt=""
              className="object-contain shrink-0 self-stretch my-auto w-5 aspect-square"
            />
            <p>Copyright Rimel 2022. All right reserved</p>
          </div>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
