/**
 * This code was generated by Builder.io.
 */
import React from "react";

const HeroBanner = () => {
  return (
    <section className="flex flex-col ml-5 w-[79%] max-md:ml-0 max-md:w-full">
      <div className="overflow-hidden grow pt-4 pl-16 mt-10 w-full bg-black max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          <div className="flex flex-col w-[37%] max-md:ml-0 max-md:w-full">
            <div className="flex flex-col items-start self-stretch my-auto w-full text-base text-neutral-50 max-md:mt-10">
              <div className="flex gap-6 items-center text-center">
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/e8adddedf9e0086e1c49a1657979167f01fb10f4a948b8533d9ffa9838db77fe?placeholderIfAbsent=true&apiKey=a7423420d6024871abbabbd8b3aee7fb"
                  alt=""
                  className="object-contain shrink-0 self-stretch my-auto w-10 aspect-[0.82]"
                />
                <p className="self-stretch my-auto w-[126px]">
                  iPhone 14 Series
                </p>
              </div>
              <h2 className="self-stretch mt-5 text-5xl font-semibold tracking-widest leading-[60px] max-md:text-4xl max-md:leading-[56px]">
                Up to 10% off Voucher
              </h2>
              <a
                href="/shop"
                className="flex gap-2 items-center mt-6 font-medium text-center"
              >
                <span className="flex flex-col self-stretch my-auto w-[81px]">
                  <span className="self-start">Shop Now</span>
                  <span className="mt-1 border border-solid bg-neutral-50 border-neutral-50 min-h-[1px] w-[81px]"></span>
                </span>
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/7a9f9190215df855e46de68e25db2cebf222e4b26191868239034c2f0ce1ceb8?placeholderIfAbsent=true&apiKey=a7423420d6024871abbabbd8b3aee7fb"
                  alt=""
                  className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
                />
              </a>
            </div>
          </div>
          <div className="flex flex-col ml-5 w-[63%] max-md:ml-0 max-md:w-full">
            <div className="flex relative flex-col items-start pb-3.5 w-full min-h-[328px] max-md:mt-10 max-md:max-w-full">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/b3bab3b87dfdbc6d218a42302584941073101b73142631e80552ef175e4d27aa?placeholderIfAbsent=true&apiKey=a7423420d6024871abbabbd8b3aee7fb"
                alt="Hero banner background"
                className="object-cover absolute inset-0 size-full"
              />
              <nav className="flex overflow-hidden relative z-10 flex-col self-end px-3 pt-5 pb-2.5 mt-0 w-56 max-w-full text-sm text-center rounded bg-black bg-opacity-0 text-neutral-50">
                <ul className="flex flex-col items-start">
                  <li className="flex gap-4 items-center self-stretch">
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/d4d3933bd60bc7f03e80195cff61581a8fb5573107350371a713dbfa0482821b?placeholderIfAbsent=true&apiKey=a7423420d6024871abbabbd8b3aee7fb"
                      alt=""
                      className="object-contain shrink-0 self-stretch my-auto w-8 aspect-square"
                    />
                    <a href="/account">Manage My Account</a>
                  </li>
                  <li className="flex gap-4 items-center mt-3.5">
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/1ca2606808d70f6c17d0a81b6b0bf390fd5c6c089fad99d24dbb560cee45a8d5?placeholderIfAbsent=true&apiKey=a7423420d6024871abbabbd8b3aee7fb"
                      alt=""
                      className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
                    />
                    <a href="/orders">My Order</a>
                  </li>
                  <li className="flex gap-4 items-center mt-3.5">
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/6472c4557bb8bee05e752b7ffa158b25fce1aedbcd24e87ee51342996186b596?placeholderIfAbsent=true&apiKey=a7423420d6024871abbabbd8b3aee7fb"
                      alt=""
                      className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
                    />
                    <a href="/cancellations">My Cancellations</a>
                  </li>
                  <li className="flex gap-4 items-center mt-3.5">
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/943c84ae3047cf3e3844a45ef6f5c62cb367d6032aaa74048785a1d185e49909?placeholderIfAbsent=true&apiKey=a7423420d6024871abbabbd8b3aee7fb"
                      alt=""
                      className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
                    />
                    <a href="/reviews">My Reviews</a>
                  </li>
                  <li className="flex gap-4 items-center mt-3.5 whitespace-nowrap">
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/5dd4ef2221a26eb97c44021b855f72d1aa05086d707c891b3a9c34b08b015240?placeholderIfAbsent=true&apiKey=a7423420d6024871abbabbd8b3aee7fb"
                      alt=""
                      className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
                    />
                    <a href="/logout">Logout</a>
                  </li>
                </ul>
              </nav>
              <div className="flex relative z-10 gap-3 justify-center items-center mt-40 max-md:mt-10">
                <button
                  className="flex shrink-0 self-stretch my-auto w-3 h-3 rounded-full bg-white bg-opacity-50 fill-white"
                  aria-label="Slide 1"
                ></button>
                <button
                  className="flex shrink-0 self-stretch my-auto w-3 h-3 rounded-full bg-white bg-opacity-50 fill-white"
                  aria-label="Slide 2"
                ></button>
                <button
                  className="flex shrink-0 self-stretch my-auto w-3.5 h-3.5 rounded-full border-2 border-white border-solid stroke-[2px] stroke-white"
                  aria-label="Slide 3 (active)"
                ></button>
                <button
                  className="flex shrink-0 self-stretch my-auto w-3 h-3 rounded-full bg-white bg-opacity-50 fill-white"
                  aria-label="Slide 4"
                ></button>
                <button
                  className="flex shrink-0 self-stretch my-auto w-3 h-3 rounded-full bg-white bg-opacity-50 fill-white"
                  aria-label="Slide 5"
                ></button>
              </div>
              <div
                className="flex relative shrink-0 -mt-3 w-2.5 h-2.5 bg-red-500 rounded-full fill-red-500 max-md:ml-1.5"
                aria-hidden="true"
              ></div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default HeroBanner;
