/**
 * This code was generated by Builder.io.
 */
import React from "react";

const IconButton = ({ icon, alt, fillColor = "" }) => {
  return (
    <button aria-label={alt} className="focus:outline-none">
      <img
        loading="lazy"
        src={icon}
        alt=""
        className={`object-contain shrink-0 self-stretch my-auto w-8 aspect-square ${fillColor}`}
      />
    </button>
  );
};

export default IconButton;
