/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import TopBanner from "./TopBanner";
import Footer from "./Footer";

const Layout = ({ children }) => {
  return (
    <div className="flex overflow-hidden flex-col bg-white">
      <TopBanner />
      <Header />
      <main>{children}</main>
      <Footer />
    </div>
  );
};

export default Layout;
