/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Layout from "../../contact-page/Layout";

function ContactPage() {
  return <Layout />;
}

export default ContactPage;
