/**
 * This code was generated by Builder.io.
 */
"use client"
import React , {useEffect, useState} from "react";
import LanguageSelector from "./LanguageSelector";
import SearchBar from "./SearchBar";
import IconButton from "./IconButton";
import { useUser } from "../../context/UserContext";
import AccountDropdown from "./account-dropdown";
import { ShoppingBag } from 'lucide-react'
function Header() {

  const { user } = useUser();

  


  return (
    <header className="flex flex-col bg-white">
      {/* Phần toàn bộ nền đen */}
      <div className="flex justify-center items-center px-16 py-3 w-full bg-black text-neutral-50 text-sm max-md:px-5">
        <div className="flex justify-between items-center w-full max-w-7xl">
          <span className="text-neutral-50 font-medium text-center mx-auto">
            Summer Sale For All Swim Suits And Free Express Delivery - OFF 50%! &nbsp;
            <a
              href="/home-page"
              className="font-semibold underline text-neutral-50"
            >
              Shop Now
            </a>
          </span>
          <div className="ml-auto">
            <LanguageSelector />
          </div>
        </div>
      </div>

      <nav className="flex justify-between items-center px-16 py-6 max-md:flex-col max-md:px-5 max-md:items-start">
        <div className="flex items-center gap-10">
          <ShoppingBag className="h-8 w-8 text-black-500 mr-2" />
            <h1 className="text-3xl font-bold text-black-500">Shop VN</h1>
          <ul className="flex gap-8 text-base">
            <li>
              <a href="/home-page" className="hover:underline">
                Home
              </a>
            </li>
            <li>
              <a href="/contact" className="hover:underline">
                Contact
              </a>
            </li>
            <li>
              <a href="/about" className="hover:underline">
                About
              </a>
            </li>
            <li>
              <a href="/login" className="hover:underline">
                Sign Up
              </a>
            </li>
            <li>
              <a href="/wishlist" className="hover:underline">
                Wish List 
              </a>
            </li>
          </ul>
        </div>

        <div className="flex items-center gap-6">
          <SearchBar />
          <div className="flex gap-4">
            <a href="/wishlist">
              <IconButton
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/2f46b01d8f56846dabad72a61fd444f3085a8b624cfad99f0b703fb6b78182f5?placeholderIfAbsent=true&apiKey=907845159c31450ca87b5b226dbf1f02"
                alt="Wishlist"
              />
            </a>
            <a href="/cart">
              <IconButton
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/f1602ef0e88675df931f73ee88ccd85c7a919ff3264f5e5c09b7ad94b1f6df9c?placeholderIfAbsent=true&apiKey=907845159c31450ca87b5b226dbf1f02"
                alt="Cart"
              
              />
            </a>
            {user ? ( // Nếu có thông tin user thì hiển thị dropdown
              <AccountDropdown user={user} />
            ) : ( // Nếu chưa có user thì hiển thị nút đăng nhập
              <a href="/login">
                <IconButton
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/505a01368e57ac667ecd551fd161eb3fa8202cee72841e5b11d9f712055e4607?placeholderIfAbsent=true&apiKey=907845159c31450ca87b5b226dbf1f02"
                  alt="User profile"
                />
              </a>
            )}


          </div>
        </div>
      </nav>

      {/* Line separator */}
      <div className="w-full bg-black border border-black opacity-30" />
    </header>
  );
}

export default Header;
