/**
 * This code was generated by Builder.io.
 */
"use client"
import React , {useEffect, useState} from "react";
import LanguageSelector from "./LanguageSelector";
import SearchBar from "./SearchBar";
import IconButton from "./IconButton";
import { useUser } from "../../context/UserContext";
import AccountDropdown from "./account-dropdown";
import { ShoppingBag } from 'lucide-react'

import { Button } from "../../components/ui/button"
function Header() {

  const { user } = useUser();

  const menuData = [
    {
      label: "Liên hệ",
      href: "/contact",
    },
    {
      label: "Giới thiệu",
      href: "/about",
    },
    {
      label: "Yêu thích",
      href: "/whish-list",
    },
    {
      label: "Đăng ký",
      href: "/register",
    },
    {
      label: "Đăng nhập",
      href: "/login",
    }
  ]

  

  return (
    
    
    <div className="mt-[100px]">
      <header className="fixed top-0 z-50 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
      {/* Promotional Banner */}
      <div className="bg-primary text-primary-foreground">
        <div className="container flex h-10 items-center justify-between px-4 sm:px-6 lg:px-8">
          <p className="text-sm font-medium">
            Summer Sale For All Swim Suits And Free Express Delivery - OFF 50%!{" "}
            <Button variant="link" className="h-auto p-0 text-primary-foreground underline-offset-4 hover:underline">
              Shop Now
            </Button>
          </p>
          <div className="ml-auto">
            <select className="bg-transparent text-sm font-medium text-primary-foreground focus:outline-none">
              <option value="en">English</option>
              <option value="fr">French</option>
              <option value="de">German</option>
            </select>
          </div>
        </div>
      </div>

      {/* Main Navigation */}
      <div className="container px-4 sm:px-6 lg:px-8">
        <div className="flex h-16 items-center justify-between">
          <div className="flex items-center gap-8">
            <div className="flex items-center gap-2">
              <a href="/home-page" className="flex">
                <ShoppingBag className="h-6 w-6" />
                <span className="text-xl font-bold">Shop VN</span>
              </a>
            </div>
            <nav className="hidden md:flex items-center gap-6">
              {menuData.map((item) => (
                <a 
                className="text-foreground/60 hover:text-foreground"
                href={item.href}>
                  {item.label}
                </a>
              ))}
            </nav>
          </div>

          <div className="flex items-center gap-6">
          <SearchBar />
          <div className="flex gap-4">
            <a href="/wishlist">
              <IconButton
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/2f46b01d8f56846dabad72a61fd444f3085a8b624cfad99f0b703fb6b78182f5?placeholderIfAbsent=true&apiKey=907845159c31450ca87b5b226dbf1f02"
                alt="Wishlist"
              />
            </a>
            <a href="/cart">
              <IconButton
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/f1602ef0e88675df931f73ee88ccd85c7a919ff3264f5e5c09b7ad94b1f6df9c?placeholderIfAbsent=true&apiKey=907845159c31450ca87b5b226dbf1f02"
                alt="Cart"
              
              />
            </a>
            {user ? ( // Nếu có thông tin user thì hiển thị dropdown
              <AccountDropdown user={user} />
            ) : ( // Nếu chưa có user thì hiển thị nút đăng nhập
              <a href="/login">
                <IconButton
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/505a01368e57ac667ecd551fd161eb3fa8202cee72841e5b11d9f712055e4607?placeholderIfAbsent=true&apiKey=907845159c31450ca87b5b226dbf1f02"
                  alt="User profile"
                />
              </a>
            )}


          </div>
        </div>
        </div>
      </div>
    </header>
    </div>
  );
}

export default Header;
