/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/U80UQfIqSfj
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";
import { useState, useMemo, useEffect } from "react";
import Link from "next/link"
import { Sheet, SheetTrigger, SheetContent } from "../../components/ui/sheet"
import { Button } from "../../components/ui/button"
import { Breadcrumb, BreadcrumbList, BreadcrumbItem, BreadcrumbLink, BreadcrumbSeparator, BreadcrumbPage } from "../../components/ui/breadcrumb"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem } from "../../components/ui/dropdown-menu"
import { Card, CardHeader, CardTitle , CardContent } from "../../components/ui/card"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "../../components/ui/table"
import { Dialog, DialogTrigger, DialogContent, DialogHeader, DialogTitle, DialogFooter, DialogClose } from "../../components/ui/dialog";
import Menu from "../component/menu"
import AddSupplierDialog from "../../components/component/addSupplier"
import { Label } from "../../components/ui/label";
import supplierAPI from "../../api/supplier";
import { Textarea } from "../../components/ui/textarea";
import { Input } from "../../components/ui/input";
import Navbar from "../component/navbar";
import {useStore} from '../../context/StoreContext'
import sellerAPI from "../../api/seller"
import Pagination from './pagination'
import { showConfirmAlert, showSuccessAlert, showErrorAlert } from "../../utils/reactSweetAlert";


export default function Supplier() {
  const [suppliers, setSuppliers] = useState([]);
  const [editingSupplier, setEditingSupplier] = useState(null);
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [formData, setFormData] = useState({
    supplierName: '',
    email: '',
    phone: '',
    fax: '',
    address: ''
  });
  const { storeId } = useStore();
  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 5;

  useEffect(() => {
    if(storeId){
      console.log("Store Id: ", storeId)
      const fetchSuppliers = async () => {
        try {
          const response = await sellerAPI.supplier.getAllSuppliers(storeId);
          console.log("Suppliers response:", response);
          if(response.statusCode === 200){
            console.log("Data structure:", response.data);
            setSuppliers(response.data);
            
          }else {
            console.error("Error fetching: ", response.message);
            setSuppliers([]);
          }
        } catch (error) {
          console.error("Failed to fetch suppliers", error);
          setSuppliers([]);
        }
      };
      fetchSuppliers();
    }else {
      console.log("storeId is null, cannot fetch suppliers.");
    }
  }, [storeId]);

  useEffect(() => {
    if (editingSupplier) {
      console.log("Editing Supplier ID:", editingSupplier.supplierId);
      setFormData({
        supplierName: editingSupplier.supplierName || '',
        email: editingSupplier.email || '',
        phone: editingSupplier.phone || '',
        fax: editingSupplier.fax || '',
        address: editingSupplier.address || ''
      });
    }
  }, [editingSupplier]);

  const indexOfLastSupplier = currentPage * itemsPerPage;
  const indexOfFirstSupplier = indexOfLastSupplier - itemsPerPage;

  const currentSuppliers = suppliers.slice(indexOfFirstSupplier, indexOfLastSupplier);

  const handlePageChange = (page) => {
    setCurrentPage(page);
  };

  const handleSaveSupplier = async (supplierData) => {
    try {
        if (editingSupplier) {
          console.log("Supplier id: ", editingSupplier.supplierId);
          const response = await sellerAPI.supplier.updateSupplier(editingSupplier.supplierId,supplierData);
          if(response.statusCode === 200) {
            setSuppliers((prevSuppliers) => 
              prevSuppliers.map((supplier) =>
                supplier.supplierId === editingSupplier.supplierId ? response.data : supplier
              )
            );
            showSuccessAlert("Thành công", "Nhà cung cấp đã được update thành công.");
          }
          console.log("Response từ API:", response.data);

        } else {
          const response = await sellerAPI.supplier.createSupplier(supplierData);
          if(response.statusCode === 200){
            setSuppliers((prevSuppliers) => [...prevSuppliers, response.data]);
            showSuccessAlert("Thành công", "Nhà cung cấp đã được thêm thành công.");
          }
          console.log("Response từ API:", response.data);
          console.log('Dữ liệu nhà cung cấp:', supplierData);
        }
        setEditingSupplier(null);
        setFormData({
          supplierName: '',
          email: '',
          phone: '',
          fax: '',
          address: ''
        });
      setIsDialogOpen(false);
    } catch (error) {
      console.error("Error saving supplier:", error.response ? error.response.data : error.message);
    }
  };

  const handleDeleteSupplier = async (supplierId) => {
    const result = await showConfirmAlert("Xác Nhận", "Bạn có chắc chắn muốn xóa nhà cung cấp này?");
    if(result.isConfirmed){
      try {
        const response = await sellerAPI.supplier.deleteSupplier(supplierId);
        if(response.statusCode === 200){
          setSuppliers(suppliers.filter((supplier) => supplier.supplierId !== supplierId));
          showSuccessAlert("Thành công", "Nhà cung cấp đã được xóa.");
        }
      } catch (error) {
        console.error("deleteSupplier failed", error);
        showErrorAlert("Lỗi", "Không thể xóa nhà cung cấp.");
      }
    }
    
  };

  const handleSubmit = (event) => {
    event.preventDefault();
    console.log("Editing Supplier:", editingSupplier);
    if (!editingSupplier || !editingSupplier.supplierId) {
      console.log("No supplier is being edited");
    } else{
      handleSaveSupplier(formData);
    }
    setIsDialogOpen(false);
  };

  const handleChange = (event) => {
    const { name, value } = event.target;
    setFormData((prevData) => ({
      ...prevData,
      [name]: value
    }));
  };



  return (
    (<div className="flex min-h-screen w-full flex-col bg-muted/40">
      <Menu/>
      <div className="flex flex-col sm:gap-4 sm:py-4 sm:pl-14">
        <Navbar/>
        <main className="grid flex-1 items-start gap-4 p-4 sm:px-6 sm:py-0 md:gap-8">
          <Card x-chunk="dashboard-06-chunk-0">
            <CardHeader>
              <CardTitle>Quản Lý Nhà Cung Cấp</CardTitle>
              <div className="ml-auto flex items-center gap-2">
              <AddSupplierDialog onSave={handleSaveSupplier}  storeId={storeId}className="outline"/>
              </div>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>STT</TableHead>
                    <TableHead>Tên Nhà Cung Cấp</TableHead>
                    <TableHead className="hidden sm:table-cell">Email</TableHead>
                    <TableHead className="hidden sm:table-cell">SDT</TableHead>
                    <TableHead className="hidden md:table-cell">Số Fax</TableHead>
                    <TableHead className="hidden md:table-cell">Địa chỉ</TableHead>
                    <TableHead>
                      <span className="sr-only">Actions</span>
                    </TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                 {currentSuppliers.map((supplier, index) => (
                  <TableRow key={index}>
                    <TableCell className="font-medium">{index + 1 + indexOfFirstSupplier}</TableCell>
                    <TableCell >{supplier.supplierName}</TableCell>
                    <TableCell className="hidden sm:table-cell">{supplier.email}</TableCell>
                    <TableCell className="hidden sm:table-cell">{supplier.phone}</TableCell>
                    <TableCell className="hidden md:table-cell">{supplier.fax}</TableCell>
                    <TableCell className="hidden md:table-cell">{supplier.address}</TableCell>
                    <TableCell>
                      <DropdownMenu>
                        <DropdownMenuTrigger asChild>
                          <Button aria-haspopup="true" size="icon" variant="ghost">
                            <MoveVerticalIcon className="h-4 w-4" />
                            <span className="sr-only">More</span>
                          </Button>
                        </DropdownMenuTrigger>
                        <DropdownMenuContent align="end">
                          <DropdownMenuItem onClick={() =>{ 
                              setEditingSupplier(supplier);
                              setIsDialogOpen(true);
                          }}>
                            <FilePenIcon className="h-4 w-4 mr-2" />
                            Sửa
                            
                          </DropdownMenuItem>
                          <DropdownMenuItem onClick={() => 
                              handleDeleteSupplier(supplier.supplierId)
                          }>
                            <TrashIcon className="h-4 w-4 mr-2" />
                            Xóa
                            
                          </DropdownMenuItem>
                        </DropdownMenuContent>
                      </DropdownMenu>
                    </TableCell>
                  </TableRow>
                 ))}
                </TableBody>
              </Table>
              <div className="m-3">
                <Pagination
                  currentPage={currentPage}
                  itemsPerPage={itemsPerPage}
                  totalItems={suppliers.length}
                  onPageChange={handlePageChange}
                />
              </div>
            </CardContent>
          </Card>
          <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
            <DialogContent className="sm:max-w-[600px]" aria-labelledby="dialog-edit">
              <DialogHeader>
                <DialogTitle>Sửa thông tin nhà cung cấp</DialogTitle>
              </DialogHeader>
              <form onSubmit={handleSubmit}>
                <div className="grid gap-4 py-4">
                  <div className="grid grid-cols-4 items-center gap-4">
                    <Label htmlFor="supplierName" className="text-right">
                      Tên nhà cung cấp
                    </Label>
                    <Input
                      id="supplierName"
                      name="supplierName"
                      value={formData.supplierName}
                      onChange={handleChange}
                      placeholder="Nhập tên nhà cung cấp"
                      className="col-span-3"
                      required
                    />
                  </div>
                  <div className="grid grid-cols-4 items-center gap-4">
                    <Label htmlFor="supplierName" className="text-right">
                      Email 
                    </Label>
                    <Input
                      id="email"
                      name="email"
                      value={formData.email}
                      onChange={handleChange}
                      placeholder="Nhập Email nhà cung cấp"
                      className="col-span-3"
                      required
                    />
                  </div>
                  <div className="grid grid-cols-4 items-center gap-4">
                    <Label htmlFor="supplierName" className="text-right">
                      Số điện thoại
                    </Label>
                    <Input
                      id="phone"
                      name="phone"
                      value={formData.phone}
                      onChange={handleChange}
                      placeholder="Nhập số điện thoại"
                      className="col-span-3"
                      required
                    />
                  </div>
                  <div className="grid grid-cols-4 items-center gap-4">
                    <Label htmlFor="supplierName" className="text-right">
                      Số Fax
                    </Label>
                    <Input
                      id="fax"
                      name="fax"
                      value={formData.fax}
                      onChange={handleChange}
                      placeholder="Nhập số fax"
                      className="col-span-3"
                      required
                    />
                  </div>
                  <div className="grid grid-cols-4 items-center gap-4">
                    <Label htmlFor="supplierName" className="text-right">
                      Địa chỉ
                    </Label>
                    <Input
                      id="address"
                      name="address"
                      value={formData.address}
                      onChange={handleChange}
                      placeholder="Nhập địa chỉ"
                      className="col-span-3"
                      required
                    />
                  </div>
               
                </div>
                <DialogFooter>
                  <Button type="submit">Lưu</Button>
                  <DialogClose asChild>
                    <Button variant="outline">Đóng</Button>
                  </DialogClose>
                </DialogFooter>
              </form>
            </DialogContent>
          </Dialog>
        </main>
      </div>
    </div>)
  );
}

function FilePenIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M12 22h6a2 2 0 0 0 2-2V7l-5-5H6a2 2 0 0 0-2 2v10" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
      <path d="M10.4 12.6a2 2 0 1 1 3 3L8 21l-4 1 1-4Z" />
    </svg>)
  );
}


function LineChartIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M3 3v18h18" />
      <path d="m19 9-5 5-4-4-3 3" />
    </svg>)
  );
}


function MoveVerticalIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polyline points="8 18 12 22 16 18" />
      <polyline points="8 6 12 2 16 6" />
      <line x1="12" x2="12" y1="2" y2="22" />
    </svg>)
  );
}


function Package2Icon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M3 9h18v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9Z" />
      <path d="m3 9 2.45-4.9A2 2 0 0 1 7.24 3h9.52a2 2 0 0 1 1.8 1.1L21 9" />
      <path d="M12 3v6" />
    </svg>)
  );
}


function PackageIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m7.5 4.27 9 5.15" />
      <path
        d="M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z" />
      <path d="m3.3 7 8.7 5 8.7-5" />
      <path d="M12 22V12" />
    </svg>)
  );
}


function PanelLeftIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="18" height="18" x="3" y="3" rx="2" />
      <path d="M9 3v18" />
    </svg>)
  );
}


function PlusIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>)
  );
}


function SearchIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>)
  );
}


function SettingsIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>)
  );
}


function ShoppingCartIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="8" cy="21" r="1" />
      <circle cx="19" cy="21" r="1" />
      <path
        d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
    </svg>)
  );
}


function TrashIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
    </svg>)
  );
}


function UsersIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>)
  );
}
