/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Header() {
  return (
    <header className="flex overflow-hidden gap-2.5 items-center px-2.5 text-xl text-black bg-zinc-50 min-h-[87px]">
      <div className="flex gap-3 items-center self-stretch my-auto min-w-[240px] w-[434px]">
        <h1 >Order giao hàng</h1>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/26371a01eeb418d5b02f4c7d1878632adde8ad6ceb83bf4ee44ab1a3cba5354e?placeholderIfAbsent=true&apiKey=b9ca3c09dab7473dba421305306c78ba"
          alt=""
          className="object-contain shrink-0 self-stretch my-0 ml-2 w-6 aspect-square"
        />
        <div className="self-stretch my-0 ml-2 w-[120px]">Order</div>
      </div>
    </header>
  );
}

export default Header;
