/**
 * This code was generated by Builder.io.
 */
import React from "react";
import OrderTableHeader from "./OrderTableHeader";
import OrderTableRow from "./OrderTableRow";

function OrderTable() {
  return (
    <table className="w-full border-collapse">
      <OrderTableHeader />
      <tbody>
        <OrderTableRow />
      </tbody>
    </table>
  );
}

export default OrderTable;
