/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Menu from "../../component/menu"
import Header from "./Header";
import OrderStatusBar from "./OrderStatusBar";
import OrderTable from "./OrderTable";

function OrderDelivery() {
  return (
    <div className="flex overflow-hidden flex-wrap font-medium bg-zinc-100">
      <Menu className="flex flex-col items-center gap-4 px-2 sm:py-5 shrink-0 w-64 h-full bg-white shadow-lg max-md:w-20"/>
      
      <main className="flex flex-col grow shrink-0 self-start mt-2 basis-0 w-full max-md:max-w-full p-2 max-md:p-4 ml-10 sm:ml-12 overflow-y-auto">
        <Header />
        <section className="flex overflow-hidden flex-col mt-4 mr-8 ml-8 text-xl bg-white rounded-lg border border-black border-solid pb-[888px] max-md:pb-24 max-md:mr-2.5 max-md:max-w-full">
          <OrderStatusBar />
          <OrderTable />
        </section>
      </main>
    </div>
  );
}

export default OrderDelivery;
