/**
 * This code was generated by Builder.io.
 */
import React from "react";

function OrderTableHeader() {
  const headers = [
    "Mã đơn hàng",
    "Tên hàng",
    "Tên người mua",
    "Địa chỉ",
    "Số lượng",
    "Giá",
    "Tổng",
    "Kiểm duyệt",
  ];

  return (
    <thead>
      <tr className="flex overflow-hidden flex-wrap gap-10 justify-between items-center px-5 py-8 mt-24 text-black border border-black border-solid min-h-[101px] max-md:mt-10 max-md:max-w-full">
        {headers.map((header, index) => (
          <th key={index} className="self-stretch my-auto text-left">
            {header}
          </th>
        ))}
      </tr>
    </thead>
  );
}

export default OrderTableHeader;
