/**
 * This code was generated by Builder.io.
 */
import React from "react";

function OrderStatusBar() {
  const statuses = [
    "Chờ xác nhận",
    "Chờ lấy hàng",
    "Đang giao",
    "Đã giao",
    "Đơn hủy",
  ];

  return (
    <nav className="flex overflow-hidden flex-wrap gap-10 justify-between items-center px-5 text-black rounded-xl border border-black border-solid bg-stone-50 min-h-[127px] max-md:max-w-full">
      {statuses.map((status, index) => (
        <div key={index} className="self-stretch my-auto">
          {status}
        </div>
      ))}
    </nav>
  );
}

export default OrderStatusBar;
