/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Footer() {
  return (
    <footer className="flex overflow-hidden flex-col justify-end pt-20 pr-20 pb-6 w-full bg-black max-md:pr-5 max-md:max-w-full">
      <div className="flex flex-wrap gap-10 justify-center items-start self-center max-md:max-w-full">
        <div className="flex flex-col text-neutral-50 w-[217px]">
          <div className="flex flex-col self-start">
            <div className="flex flex-col max-w-full whitespace-nowrap w-[118px]">
              <div className="w-full text-2xl font-bold tracking-wider leading-none">
                Exclusive
              </div>
              <div className="mt-6 text-xl font-medium leading-snug">
                Subscribe
              </div>
            </div>
            <div className="mt-6 text-base">Get 10% off your first order</div>
          </div>
          <form className="flex gap-8 items-center py-3 pl-4 mt-4 max-w-full text-base rounded border-solid border-[1.5px] border-neutral-50 w-[217px]">
            <label htmlFor="email" className="sr-only">
              Enter your email
            </label>
            <input
              type="email"
              id="email"
              className="self-stretch my-auto opacity-40 bg-transparent border-none"
              placeholder="Enter your email"
            />
            <button type="submit" aria-label="Subscribe">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/82bea2c24624aec83b7f465f3f7dd6459b56a1974408d3a52263051296213050?placeholderIfAbsent=true&apiKey=8529e6e5616147a184f7c00db4d45e0b"
                className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
                alt=""
              />
            </button>
          </form>
        </div>
        <nav className="flex flex-col text-neutral-50 w-[175px]">
          <h2 className="text-xl font-medium leading-snug">Support</h2>
          <address className="flex flex-col mt-6 max-w-full text-base w-[175px] not-italic">
            <p className="leading-6">
              111 Bijoy sarani, Dhaka, DH 1515, Bangladesh.
            </p>
            <p className="mt-4">exclusive@gmail.com</p>
            <p className="mt-4">+88015-88888-9999</p>
          </address>
        </nav>
        <nav className="flex flex-col text-neutral-50">
          <h2 className="text-xl font-medium leading-snug">Account</h2>
          <ul className="flex flex-col mt-6 text-base list-none p-0">
            <li>
              <a href="#">My Account</a>
            </li>
            <li className="mt-4">
              <a href="#">Login / Register</a>
            </li>
            <li className="mt-4">
              <a href="#">Cart</a>
            </li>
            <li className="mt-4">
              <a href="#">Wishlist</a>
            </li>
            <li className="mt-4">
              <a href="#">Shop</a>
            </li>
          </ul>
        </nav>
        <nav className="flex flex-col text-neutral-50">
          <h2 className="text-xl font-medium leading-snug">Quick Link</h2>
          <ul className="flex flex-col mt-6 text-base list-none p-0">
            <li>
              <a href="#">Privacy Policy</a>
            </li>
            <li className="mt-4">
              <a href="#">Terms Of Use</a>
            </li>
            <li className="mt-4">
              <a href="#">FAQ</a>
            </li>
            <li className="mt-4">
              <a href="#">Contact</a>
            </li>
          </ul>
        </nav>
        <div className="flex flex-col">
          <div className="flex flex-col">
            <h2 className="text-xl font-medium leading-snug text-neutral-50">
              Download App
            </h2>
            <div className="flex flex-col mt-6">
              <p className="text-xs font-medium opacity-70 text-neutral-50">
                Save $3 with App New User Only
              </p>
              <div className="flex gap-2 items-center mt-2">
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/eea58754d717cfcc9af195e6cb2ee0d2841c30fecd62d9cef8132dc530d1448d?placeholderIfAbsent=true&apiKey=8529e6e5616147a184f7c00db4d45e0b"
                  className="object-contain shrink-0 self-stretch my-auto w-20 aspect-square"
                  alt="QR Code"
                />
                <div className="flex flex-col self-stretch my-auto w-[110px]">
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/f5a0011e5a16669b37837b7d57675eb91b8099c37f37be9c4d12e698e193d49d?placeholderIfAbsent=true&apiKey=8529e6e5616147a184f7c00db4d45e0b"
                    className="object-contain max-w-full aspect-[2.75] w-[110px]"
                    alt="Google Play Store"
                  />
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/e815fcb4af82376341f7e3002c89152cb3b9e6d29e4d0efcb4e01999aa39bcc1?placeholderIfAbsent=true&apiKey=8529e6e5616147a184f7c00db4d45e0b"
                    className="object-contain mt-1 max-w-full aspect-[2.75] w-[110px]"
                    alt="Apple App Store"
                  />
                </div>
              </div>
            </div>
          </div>
          <div className="flex gap-6 items-start self-start mt-6">
            <a href="#" aria-label="Facebook">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/30ef1881c8ba382ad841b10dec22c4728e1ac56594cd8fd1b8fc54e4c0c91052?placeholderIfAbsent=true&apiKey=8529e6e5616147a184f7c00db4d45e0b"
                className="object-contain shrink-0 w-6 aspect-square"
                alt=""
              />
            </a>
            <a href="#" aria-label="Twitter">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/d5ed0e9349f0808e3f648ff40ecaf46350a40511099f0f6a044c3dcfc4be3bf2?placeholderIfAbsent=true&apiKey=8529e6e5616147a184f7c00db4d45e0b"
                className="object-contain shrink-0 w-6 aspect-square"
                alt=""
              />
            </a>
            <a href="#" aria-label="Instagram">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/d0b67f52bb53b8c3b436cfc50867157e647c1cc5fa6f7cc373ba309b35f3d286?placeholderIfAbsent=true&apiKey=8529e6e5616147a184f7c00db4d45e0b"
                className="object-contain shrink-0 w-6 aspect-square"
                alt=""
              />
            </a>
            <a href="#" aria-label="LinkedIn">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/017f03fd6271e23e94e189db8506f53ec67e53623ecac07e20b0cc0e64aa481c?placeholderIfAbsent=true&apiKey=8529e6e5616147a184f7c00db4d45e0b"
                className="object-contain shrink-0 w-6 aspect-square"
                alt=""
              />
            </a>
          </div>
        </div>
      </div>
      <div className="flex flex-col items-center mt-16 w-full max-md:mt-10 max-md:max-w-full">
        <div className="flex flex-col max-w-full w-[1440px]">
          <div className="shrink-0 h-px bg-white border border-white border-solid opacity-40 max-md:max-w-full" />
        </div>
        <div className="flex gap-3 items-center mt-4 text-base text-white">
          <div className="flex gap-1.5 items-center self-stretch my-auto min-w-[240px]">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/31106ccf7f9b47cd488fefba20d096b1d7303864f7c967b7ee43968ac28ce833?placeholderIfAbsent=true&apiKey=8529e6e5616147a184f7c00db4d45e0b"
              className="object-contain shrink-0 self-stretch my-auto w-5 aspect-square"
              alt=""
            />
            <p className="self-stretch my-auto">
              Copyright Rimel 2022. All right reserved
            </p>
          </div>
        </div>
      </div>
    </footer>
  );
}

export default Footer;
