/**
 * This code was generated by Builder.io.
 */
import React from "react";

function AppDownload() {
  return (
    <div className="flex flex-col">
      <h2 className="text-xl font-medium leading-snug text-neutral-50">
        Download App
      </h2>
      <div className="flex flex-col mt-6">
        <p className="text-xs font-medium opacity-70 text-neutral-50">
          Save $3 with App New User Only
        </p>
        <div className="flex gap-2 items-center mt-2">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/eea58754d717cfcc9af195e6cb2ee0d2841c30fecd62d9cef8132dc530d1448d?apiKey=8529e6e5616147a184f7c00db4d45e0b&"
            alt="QR Code"
            className="object-contain shrink-0 self-stretch my-auto w-20 aspect-square"
          />
          <div className="flex flex-col self-stretch my-auto w-[110px]">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/f5a0011e5a16669b37837b7d57675eb91b8099c37f37be9c4d12e698e193d49d?apiKey=8529e6e5616147a184f7c00db4d45e0b&"
              alt="Download on the App Store"
              className="object-contain max-w-full aspect-[2.75] w-[110px]"
            />
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/e815fcb4af82376341f7e3002c89152cb3b9e6d29e4d0efcb4e01999aa39bcc1?apiKey=8529e6e5616147a184f7c00db4d45e0b&"
              alt="Get it on Google Play"
              className="object-contain mt-1 max-w-full aspect-[2.75] w-[110px]"
            />
          </div>
        </div>
      </div>
    </div>
  );
}

export default AppDownload;
