/**
 * This code was generated by Builder.io.
 */
"use client"
import React from "react";

function ErrorPage({ statusCode = 404, message = "Trang không tồn tại" }) {
  const handleBack = () => {
    if (window.history.length > 1) {
      window.history.back();
    } else {
      window.location.href = "/login"; // Nếu không có lịch sử, chuyển về trang chủ
    }
  };

  return (
    <main className="flex flex-col items-center justify-center h-screen text-center bg-gray-100">
      <nav
        aria-label="Breadcrumb"
        className="flex gap-3 items-center text-sm text-gray-600"
      >
        <a href="/login" className="opacity-70 hover:underline">
          Đăng nhập
        </a>
        <span className="text-gray-800">Lỗi {statusCode}</span>
      </nav>
      <section className="flex flex-col items-center mt-10">
        <h1 className="text-9xl font-bold leading-none bg-clip-text text-transparent bg-gradient-to-r from-red-500 to-pink-500 drop-shadow-lg max-md:text-6xl">
          Lỗi {statusCode}
        </h1>
        <h2 className="text-4xl font-medium text-gray-800 mt-4 max-md:text-2xl">
          {message}
        </h2>
      </section>
      <button
        className="px-12 py-4 mt-10 text-base font-semibold bg-gradient-to-r from-red-400 to-pink-500 hover:from-pink-500 hover:to-red-500 rounded-full text-white shadow-lg transform transition-transform duration-300 hover:scale-105 max-md:px-5"
        onClick={handleBack}
      >
        Trở về trang trước
      </button>
    </main>
  );
}

export default ErrorPage;
