/**
 * This code was generated by Builder.io.
 */
import React from "react";

function FooterColumn({ title, items }) {
  return (
    <div className="flex flex-col text-neutral-50 w-[175px]">
      <h2 className="text-xl font-medium leading-snug">{title}</h2>
      <ul className="flex flex-col mt-6 max-w-full text-base w-[175px]">
        {items.map((item, index) => (
          <li key={index} className={index > 0 ? "mt-4" : ""}>
            {item}
          </li>
        ))}
      </ul>
    </div>
  );
}

export default FooterColumn;
