/**
 * This code was generated by Builder.io.
 */
import React from "react";

function LanguageSelector() {
  return (
    <div className="flex gap-1.5 justify-center items-center whitespace-nowrap">
      <span className="self-stretch my-auto">English</span>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/086dd669bbad3e4fcefbf1d6392f774b77d8ae772723fe01a24425e01abcaf04?apiKey=8529e6e5616147a184f7c00db4d45e0b&"
        alt=""
        className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
      />
    </div>
  );
}

export default LanguageSelector;
