/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "../../components/component/Header";

import Footer from "./Footer";

function Layout({ children }) {
  return (
    <div className="flex overflow-hidden flex-col bg-white">
      <Header />
      <div className="" />
      {children}
      <Footer />
    </div>
  );
}

export default Layout;
