/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SearchBar from "./SearchBar";

function Navigation() {
  const navItems = ["Home", "Contact", "About", "Sign Up"];

  return (
    <nav className="flex flex-wrap gap-10 items-center self-center mt-10 max-md:max-w-full">
      <div className="flex flex-wrap gap-10 items-start self-stretch my-auto text-black min-w-[240px] max-md:max-w-full">
        <h1 className="text-2xl font-bold tracking-wider leading-none whitespace-nowrap w-[118px]">
          Exclusive
        </h1>
        <ul className="flex gap-10 items-start text-base text-center min-w-[240px]">
          {navItems.map((item, index) => (
            <li
              key={index}
              className={`w-${
                item.length === 4 ? "12" : "[61px]"
              } whitespace-nowrap`}
            >
              <a href={`#${item.toLowerCase()}`}>{item}</a>
            </li>
          ))}
        </ul>
      </div>
      <div className="flex gap-6 items-center self-stretch my-auto min-w-[240px]">
        <SearchBar />
        <div className="flex gap-4 justify-center items-center self-stretch my-auto">
          {[
            "https://cdn.builder.io/api/v1/image/assets/TEMP/850597cc14d3bfef027aa097fc5bca3ac1b650d683dc1d3c8c0134d5cd9a061d?apiKey=8529e6e5616147a184f7c00db4d45e0b&",
            "https://cdn.builder.io/api/v1/image/assets/TEMP/f1602ef0e88675df931f73ee88ccd85c7a919ff3264f5e5c09b7ad94b1f6df9c?apiKey=8529e6e5616147a184f7c00db4d45e0b&",
            "https://cdn.builder.io/api/v1/image/assets/TEMP/505a01368e57ac667ecd551fd161eb3fa8202cee72841e5b11d9f712055e4607?apiKey=8529e6e5616147a184f7c00db4d45e0b&",
          ].map((src, index) => (
            <img
              key={index}
              loading="lazy"
              src={src}
              alt=""
              className="object-contain shrink-0 self-stretch my-auto w-8 aspect-square"
            />
          ))}
        </div>
      </div>
    </nav>
  );
}

export default Navigation;
