/**
 * This code was generated by Builder.io.
 */
import React from "react";

function SearchBar() {
  return (
    <form className="flex flex-col justify-center items-center self-stretch py-2 pr-3 pl-5 my-auto text-xs text-black rounded bg-neutral-100 min-w-[240px]">
      <div className="flex gap-9 justify-center items-center">
        <label htmlFor="search" className="sr-only">
          Search
        </label>
        <input
          type="text"
          id="search"
          placeholder="What are you looking for?"
          className="self-stretch my-auto opacity-50 bg-transparent border-none outline-none"
        />
        <button type="submit" aria-label="Search">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/7a36546edd30f9649053810fdbf6c98d92541e863e7b8b10ab13af855343b34e?apiKey=8529e6e5616147a184f7c00db4d45e0b&"
            alt=""
            className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
          />
        </button>
      </div>
    </form>
  );
}

export default SearchBar;
