/**
 * This code was generated by Builder.io.
 */
import React from "react";

function SocialLinks() {
  const socialIcons = [
    "https://cdn.builder.io/api/v1/image/assets/TEMP/30ef1881c8ba382ad841b10dec22c4728e1ac56594cd8fd1b8fc54e4c0c91052?apiKey=8529e6e5616147a184f7c00db4d45e0b&",
    "https://cdn.builder.io/api/v1/image/assets/TEMP/f15e952bed544dbff11a3269a554cc2fc49d20a3e895cb261e598605d69cee62?apiKey=8529e6e5616147a184f7c00db4d45e0b&",
    "https://cdn.builder.io/api/v1/image/assets/TEMP/d0b67f52bb53b8c3b436cfc50867157e647c1cc5fa6f7cc373ba309b35f3d286?apiKey=8529e6e5616147a184f7c00db4d45e0b&",
    "https://cdn.builder.io/api/v1/image/assets/TEMP/017f03fd6271e23e94e189db8506f53ec67e53623ecac07e20b0cc0e64aa481c?apiKey=8529e6e5616147a184f7c00db4d45e0b&",
  ];

  return (
    <div className="flex gap-6 items-start self-start mt-6">
      {socialIcons.map((src, index) => (
        <a key={index} href="#" aria-label={`Social media link ${index + 1}`}>
          <img
            loading="lazy"
            src={src}
            alt=""
            className="object-contain shrink-0 w-6 aspect-square"
          />
        </a>
      ))}
    </div>
  );
}

export default SocialLinks;
