/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "../../components/component/Header";
import CartItems from "./CartItems"
import ShoppingCart from "./shopping-cart"
import Footer from "./Footer";

function CartPage() {
  
  return (
    <main className="flex overflow-hidden flex-col bg-white">
      <Header />
      <div className="" />
      {/* <section className="flex flex-col self-center mt-20 w-full max-w-[1170px] max-md:mt-10 max-md:max-w-full">
        <nav
          className="flex gap-3 items-center self-start text-sm text-black whitespace-nowrap"
          aria-label="Breadcrumb"
        >
          <a href="#" className="self-stretch my-auto opacity-50">
            Home
          </a>
          <span className="self-stretch my-auto">Cart</span>
        </nav>
        <div className="flex flex-col mt-20 w-full max-md:mt-10 max-md:max-w-full">

          
        </div>
      </section> */}
      <ShoppingCart/>
      <Footer />
    </main>
  );
}

export default CartPage;
