/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import CartItems from "./CartItems";
import CartSummary from "./CartSummary";
import Footer from "./Footer";

function CartPage() {
  return (
    <main className="flex overflow-hidden flex-col bg-white">
      <Header />
      <div className="mt-4 w-full bg-black border border-black border-solid opacity-30 min-h-[1px] max-md:max-w-full" />
      <section className="flex flex-col self-center mt-20 w-full max-w-[1170px] max-md:mt-10 max-md:max-w-full">
        <nav
          className="flex gap-3 items-center self-start text-sm text-black whitespace-nowrap"
          aria-label="Breadcrumb"
        >
          <a href="#" className="self-stretch my-auto opacity-50">
            Home
          </a>
          <span className="self-stretch my-auto">Cart</span>
        </nav>
        <div className="flex flex-col mt-20 w-full max-md:mt-10 max-md:max-w-full">
          <CartItems />
          <CartSummary />
        </div>
      </section>
      <Footer />
    </main>
  );
}

export default CartPage;
