/**
 * This code was generated by Builder.io.
 */
import React from "react";

function IconGroup() {
  const icons = [
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/2f46b01d8f56846dabad72a61fd444f3085a8b624cfad99f0b703fb6b78182f5?placeholderIfAbsent=true&apiKey=907845159c31450ca87b5b226dbf1f02",
      alt: "Wishlist",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/1d49936bb7e7947951a24074df0be75fc667e72893b1780ac9e82c006a87816b?placeholderIfAbsent=true&apiKey=907845159c31450ca87b5b226dbf1f02",
      alt: "Cart",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/505a01368e57ac667ecd551fd161eb3fa8202cee72841e5b11d9f712055e4607?placeholderIfAbsent=true&apiKey=907845159c31450ca87b5b226dbf1f02",
      alt: "User account",
    },
  ];

  return (
    <div className="flex gap-4 justify-center items-center self-stretch my-auto">
      {icons.map((icon, index) => (
        <button key={index} aria-label={icon.alt}>
          <img
            loading="lazy"
            src={icon.src}
            className="object-contain shrink-0 self-stretch my-auto w-8 aspect-square"
            alt=""
          />
        </button>
      ))}
    </div>
  );
}

export default IconGroup;
