/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Layout from "./Layout";
import Story from "./Story";
import Stats from "./Stats";
import Team from "./Team";
import Features from "./Features";

function About() {
  return (
    <Layout>
      <div className="flex gap-3 items-center self-start   text-sm text-black whitespace-nowrap">
        <a href="/" className="self-stretch my-auto opacity-50">
          Home
        </a>
        <span className="self-stretch my-auto">About</span>
      </div>
      <Story />
      <Stats />
      <Team />
      <div className="flex gap-3 items-center self-center mt-10">
        <div className="flex shrink-0 self-stretch my-auto w-3 h-3 rounded-full bg-black bg-opacity-30 fill-black" />
        <div className="flex shrink-0 self-stretch my-auto w-3 h-3 rounded-full bg-black bg-opacity-30 fill-black" />
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/92b177d4489b789ca67cd5f3caa2fe9bf63df0a7d703e2d52fb18370f3559c3c?placeholderIfAbsent=true&apiKey=8529e6e5616147a184f7c00db4d45e0b"
          alt=""
          className="object-contain shrink-0 self-stretch my-auto w-4 aspect-square"
        />
        <div className="flex shrink-0 self-stretch my-auto w-3 h-3 rounded-full bg-black bg-opacity-30 fill-black" />
        <div className="flex shrink-0 self-stretch my-auto w-3 h-3 rounded-full bg-black bg-opacity-30 fill-black" />
      </div>
      <Features />
    </Layout>
  );
}

export default About;
