/**
 * This code was generated by Builder.io.
 */
import React from "react";
import FeatureCard from "./FeatureCard";

function Features() {
  const features = [
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/0d1d62fe1e7dbed0d5387ea55717073d41fe8078ca29c6019b426bf4176fac9c?placeholderIfAbsent=true&apiKey=8529e6e5616147a184f7c00db4d45e0b",
      title: "FREE AND FAST DELIVERY",
      description: "Free delivery for all orders over $140",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/b9026c1ec0051495a95a2edf70c4f73f6cca2ad641fc42222533aaec6eb7e6cb?placeholderIfAbsent=true&apiKey=8529e6e5616147a184f7c00db4d45e0b",
      title: "24/7 CUSTOMER SERVICE",
      description: "Friendly 24/7 customer support",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/4df5a08644ff18cdd1154dcda493d6b3d4600e259243067d386835aff0657f0c?placeholderIfAbsent=true&apiKey=8529e6e5616147a184f7c00db4d45e0b",
      title: "MONEY BACK GUARANTEE",
      description: "We return money within 30 days",
    },
  ];

  return (
    <div className="flex flex-wrap gap-10 justify-center items-center mt-36 ml-28 text-black max-md:mt-10 max-md:max-w-full">
      {features.map((feature, index) => (
        <FeatureCard key={index} {...feature} />
      ))}
    </div>
  );
}

export default Features;
