/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SearchBar from "./SearchBar";
import IconGroup from "./IconGroup";

function Header() {
  return (
    <header className="flex flex-wrap gap-10 items-center self-center mt-10 max-md:max-w-full">
      <div className="flex flex-wrap gap-10 items-start self-stretch my-auto text-black min-w-[240px] max-md:max-w-full">
        <h1 className="text-2xl font-bold tracking-wider leading-none whitespace-nowrap w-[118px]">
          Exclusive
        </h1>
        <nav className="flex gap-10 items-start text-base text-center min-w-[240px]">
          <a href="/" className="w-12 whitespace-nowrap">
            Home
          </a>
          <a href="/contact" className="whitespace-nowrap w-[66px]">
            Contact
          </a>
          <div className="flex flex-col items-center w-12 whitespace-nowrap">
            <a href="/about">About</a>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/7c4a968e61751929cf46491fa57e5fa87f2f3c7c5d51673c41475a8954433106?placeholderIfAbsent=true&apiKey=8529e6e5616147a184f7c00db4d45e0b"
              alt=""
              className="object-contain w-12 aspect-[47.62]"
            />
          </div>
          <a href="/signup" className="w-[61px]">
            Sign Up
          </a>
        </nav>
      </div>
      <div className="flex gap-6 items-center self-stretch my-auto min-w-[240px]">
        <SearchBar />
        <IconGroup />
      </div>
    </header>
  );
}

export default Header;
