/**
 * This code was generated by Builder.io.
 */
import React from "react";

function IconGroup() {
  const icons = [
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/850597cc14d3bfef027aa097fc5bca3ac1b650d683dc1d3c8c0134d5cd9a061d?placeholderIfAbsent=true&apiKey=8529e6e5616147a184f7c00db4d45e0b",
      alt: "Wishlist",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/f1602ef0e88675df931f73ee88ccd85c7a919ff3264f5e5c09b7ad94b1f6df9c?placeholderIfAbsent=true&apiKey=8529e6e5616147a184f7c00db4d45e0b",
      alt: "Cart",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/505a01368e57ac667ecd551fd161eb3fa8202cee72841e5b11d9f712055e4607?placeholderIfAbsent=true&apiKey=8529e6e5616147a184f7c00db4d45e0b",
      alt: "Profile",
    },
  ];

  return (
    <div className="flex gap-4 justify-center items-center self-stretch my-auto">
      {icons.map((icon, index) => (
        <button key={index} aria-label={icon.alt}>
          <img
            loading="lazy"
            src={icon.src}
            alt=""
            className="object-contain shrink-0 self-stretch my-auto w-8 aspect-square"
          />
        </button>
      ))}
    </div>
  );
}

export default IconGroup;
