/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import Footer from "./Footer";

function Layout({ children }) {
  return (
    <div className="flex overflow-hidden flex-col bg-white">
      <div className="flex overflow-hidden flex-col justify-center items-end px-16 py-3 w-full text-sm bg-black text-neutral-50 max-md:px-5 max-md:max-w-full">
        <div className="flex flex-wrap gap-10 items-start max-md:max-w-full">
          <div className="flex flex-wrap gap-2 items-center min-w-[240px] max-md:max-w-full">
            <p className="self-stretch my-auto w-[474px] max-md:max-w-full">
              Summer Sale For All Swim Suits And Free Express Delivery - OFF
              50%!
            </p>
            <a
              href="#"
              className="self-stretch my-auto font-semibold leading-6 text-center underline"
            >
              ShopNow
            </a>
          </div>
          <div className="flex gap-1.5 justify-center items-center whitespace-nowrap">
            <span className="self-stretch my-auto">English</span>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/086dd669bbad3e4fcefbf1d6392f774b77d8ae772723fe01a24425e01abcaf04?placeholderIfAbsent=true&apiKey=8529e6e5616147a184f7c00db4d45e0b"
              alt=""
              className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
            />
          </div>
        </div>
      </div>
      <Header />
      <main className="flex flex-col items-start self-end mt-20 w-full max-w-[1305px] max-md:mt-10 max-md:max-w-full">
        {children}
      </main>
      <Footer />
    </div>
  );
}

export default Layout;
