/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Footer from "./Footer";
import Header from "../component/Header";
function Layout({ children }) {
  return (
    <div className="flex overflow-hidden flex-col bg-white">
      <Header/>
      <main className="flex flex-col items-center self-center  mt-20 w-full max-w-[1305px] max-md:mt-10 max-md:max-w-full">
        {children}
      </main>
      <Footer />
    </div>
  );
}

export default Layout;
