/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Story() {
  return (
    <section className="self-stretch mt-11 max-md:mt-10 max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col">
        <div className="flex flex-col w-[43%] max-md:ml-0 max-md:w-full">
          <div className="flex flex-col self-stretch my-auto max-md:mt-10 max-md:max-w-full">
            <h2 className="text-6xl font-semibold leading-none text-justify text-black tracking-[3.24px] max-md:text-4xl">
              Trang web của chúng tôi 
            </h2>
            <div className="flex flex-col mt-10 max-w-full text-base leading-7 text-black w-[525px]">
              <p className="max-md:max-w-full">
                <p className="">về người mua</p>
                Được xuất hiện vào năm 2024 , chúng tôi luôn muốn mang lại cho người dùng trải nghiệp tốt nhất
                về việc mua hàng hóa online. Hiện nay già trẻ lớn bé ai cũng muốn mua hàng nhanh chóng thuận tiện
                , mua những món đồ hữu ích cho cá nhân nhưng các cửa hàng gần nhà không ai bán ,
                và trang web được xuất hiện khi nhu cầu người dùng quá lớn , ai cũng có thể mua hàng hóa cho riêng mình
                bất kể dù gần hay xa xôi. 
              </p>
              <p className="mt-6 max-md:max-w-full">
                <p className="">Về người bán</p>
                Chúng tôi luôn muốn các mặt hàng đa dạng , nên người bán có thể đăng ký các hủ tục
                online , bán hàng online , đa dạng hàng hóa , cung cấp và nhu cầu người dùng hợp lý 
                chúng tôi muốn trang web của mình thành một cái chợ online 
              </p>
              <p className="mt-6 max-md:max-w-full">
                <p className="">Về chúng tôi</p>
                  Trang web đầu tay chúng em làm còn sai sót nhiều , cũng là tâm huyết của cả nhóm đặt biệt là trưởng nhóm 
                  , vì là trang web đầu tay có thể gọi chỉnh chu , chúng em mong các quý thầy cô thông cảm và góp ý cho chúng
                  em lấy kinh nghiệm cho các chặng đường sau này. 
              </p>
            </div>
          </div>
        </div>
        <div className="flex flex-col ml-5 w-[57%] max-md:ml-0 max-md:w-full">
          <div className="flex overflow-hidden flex-col grow w-full bg-pink-400 rounded max-md:mt-10 max-md:max-w-full">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/ff9a234331136510c155f1b24a7a62caa57d995167598454a45b2f0e0798ec78?placeholderIfAbsent=true&apiKey=8529e6e5616147a184f7c00db4d45e0b"
              alt="Exclusive store front"
              className="object-contain w-full aspect-[1.16] max-md:max-w-full"
            />
          </div>
        </div>
      </div>
    </section>
  );
}

export default Story;
