/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Story() {
  return (
    <section className="self-stretch mt-11 max-md:mt-10 max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col">
        <div className="flex flex-col w-[43%] max-md:ml-0 max-md:w-full">
          <div className="flex flex-col self-stretch my-auto max-md:mt-10 max-md:max-w-full">
            <h2 className="text-6xl font-semibold leading-none text-justify text-black tracking-[3.24px] max-md:text-4xl">
              Our Story
            </h2>
            <div className="flex flex-col mt-10 max-w-full text-base leading-7 text-black w-[525px]">
              <p className="max-md:max-w-full">
                Launced in 2015, Exclusive is South Asia's premier online
                shopping makterplace with an active presense in Bangladesh.
                Supported by wide range of tailored marketing, data and service
                solutions, Exclusive has 10,500 sallers and 300 brands and
                serves 3 millioons customers across the region.
              </p>
              <p className="mt-6 max-md:max-w-full">
                Exclusive has more than 1 Million products to offer, growing at
                a very fast. Exclusive offers a diverse assotment in categories
                ranging from consumer.
              </p>
            </div>
          </div>
        </div>
        <div className="flex flex-col ml-5 w-[57%] max-md:ml-0 max-md:w-full">
          <div className="flex overflow-hidden flex-col grow w-full bg-pink-400 rounded max-md:mt-10 max-md:max-w-full">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/ff9a234331136510c155f1b24a7a62caa57d995167598454a45b2f0e0798ec78?placeholderIfAbsent=true&apiKey=8529e6e5616147a184f7c00db4d45e0b"
              alt="Exclusive store front"
              className="object-contain w-full aspect-[1.16] max-md:max-w-full"
            />
          </div>
        </div>
      </div>
    </section>
  );
}

export default Story;
