/**
 * This code was generated by Builder.io.
 */
import React from "react";
import TeamMember from "./TeamMember";

function Team() {
  const teamMembers = [
    {
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/1c9a0cd9f923f13c47edaa36d07a0cfaa79d2d95afe70f48e573bd6df4f2fc16?placeholderIfAbsent=true&apiKey=8529e6e5616147a184f7c00db4d45e0b",
      name: "Tom Cruise",
      role: "Founder & Chairman",
      socialLinks: [
        {
          platform: "Twitter",
          icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/0218b030c06870bbf352454fc664f65e80015c251348b7a9b96f98f9869fe4d6?placeholderIfAbsent=true&apiKey=8529e6e5616147a184f7c00db4d45e0b",
          url: "#",
        },
        {
          platform: "Instagram",
          icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/3c1a0fefac87f608f4c0aae4614cc407882e4296e7e60d716ad48fdde7e2b127?placeholderIfAbsent=true&apiKey=8529e6e5616147a184f7c00db4d45e0b",
          url: "#",
        },
        {
          platform: "LinkedIn",
          icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/fa88e0ec4d85b90779c166de611103f06f0c7744640ae7496df24ef1ff5c4d83?placeholderIfAbsent=true&apiKey=8529e6e5616147a184f7c00db4d45e0b",
          url: "#",
        },
      ],
    },
    {
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/8ec9f13f712532546cf149b6590545fba751d0037a8f470ef89c052d0fecc0ec?placeholderIfAbsent=true&apiKey=8529e6e5616147a184f7c00db4d45e0b",
      name: "Emma Watson",
      role: "Managing Director",
      socialLinks: [
        {
          platform: "Twitter",
          icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/d9556820a4da1e8a11e1ae514e8355d177f285fc7ef3181e2f3d79f0f67ff57d?placeholderIfAbsent=true&apiKey=8529e6e5616147a184f7c00db4d45e0b",
          url: "#",
        },
        {
          platform: "Instagram",
          icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/3c1a0fefac87f608f4c0aae4614cc407882e4296e7e60d716ad48fdde7e2b127?placeholderIfAbsent=true&apiKey=8529e6e5616147a184f7c00db4d45e0b",
          url: "#",
        },
        {
          platform: "LinkedIn",
          icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/fa88e0ec4d85b90779c166de611103f06f0c7744640ae7496df24ef1ff5c4d83?placeholderIfAbsent=true&apiKey=8529e6e5616147a184f7c00db4d45e0b",
          url: "#",
        },
      ],
    },
    {
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/76a3e5aff29f342a81b2585145c474b743a27ede0ad2076aad905c9d66860c61?placeholderIfAbsent=true&apiKey=8529e6e5616147a184f7c00db4d45e0b",
      name: "Will Smith",
      role: "Product Designer",
      socialLinks: [
        {
          platform: "Twitter",
          icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/83da1b76d6ac1bab75f967d2d5bfd67fde73ac03a7463563e29a8c62fd3e436f?placeholderIfAbsent=true&apiKey=8529e6e5616147a184f7c00db4d45e0b",
          url: "#",
        },
        {
          platform: "Instagram",
          icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/3c1a0fefac87f608f4c0aae4614cc407882e4296e7e60d716ad48fdde7e2b127?placeholderIfAbsent=true&apiKey=8529e6e5616147a184f7c00db4d45e0b",
          url: "#",
        },
        {
          platform: "LinkedIn",
          icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/fa88e0ec4d85b90779c166de611103f06f0c7744640ae7496df24ef1ff5c4d83?placeholderIfAbsent=true&apiKey=8529e6e5616147a184f7c00db4d45e0b",
          url: "#",
        },
      ],
    },
  ];

  return (
    <div className="flex flex-wrap gap-8 items-start mt-36 max-md:mt-10">
      {teamMembers.map((member, index) => (
        <TeamMember key={index} {...member} />
      ))}
    </div>
  );
}

export default Team;
